(function(){
  var attemptKey='ekursAuthAttempts';
  var lockKey='ekursAuthLockedUntil';
  function $(id){return document.getElementById(id)}
  function show(el,type,msg){if(!el)return;el.className='auth-message show '+type;el.textContent=msg}
  function roleTarget(role){return role==='teacher'?'/ogretmen-paneli/':role==='parent'?'/veli-paneli.html':'/ogrenci/panel.html'}
  function attempts(){return Number(localStorage.getItem(attemptKey)||0)}
  function lockedUntil(){return Number(localStorage.getItem(lockKey)||0)}
  function isEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
  function setRole(role){var form=$('registerForm');if(!form)return;form.classList.remove('role-student','role-teacher','role-parent');form.classList.add('role-'+role);$('registerRole').value=role;document.querySelectorAll('[data-role-tab]').forEach(function(btn){btn.setAttribute('aria-pressed',btn.dataset.roleTab===role?'true':'false')});var note=$('roleNote');if(note)note.textContent=role==='student'?'Öğrenci hesabı veli veya öğretmen onayıyla açılır. Bu form ön başvuru oluşturur.':role==='teacher'?'Öğretmen hesabı okul/sınıf yönetimi için doğrulanır.':'Veli hesabı öğrenci takibi ve rapor görüntüleme için kullanılır.'}
  function initLogin(){var form=$('loginForm');if(!form)return;var msg=$('loginMessage');form.addEventListener('submit',function(e){e.preventDefault();var now=Date.now();if(lockedUntil()>now){show(msg,'error','Çok fazla deneme yapıldı. Lütfen birkaç dakika sonra tekrar deneyin.');return}var user=$('loginUser').value.trim();var pass=$('loginPassword').value;var role=$('loginRole').value;if(!user||!pass){show(msg,'error','Giriş bilgilerini tamamlayıp tekrar deneyin.');return}if(pass.length<4){var next=attempts()+1;localStorage.setItem(attemptKey,String(next));if(next>=5)localStorage.setItem(lockKey,String(now+3*60*1000));show(msg,'error','Giriş bilgileri hatalı, lütfen tekrar deneyin.');return}localStorage.setItem(attemptKey,'0');localStorage.setItem('ekursDemoUser',JSON.stringify({user:user,role:role,remember:$('rememberMe').checked,createdAt:new Date().toISOString()}));show(msg,'success','Giriş başarılı. Paneline yönlendiriliyorsun.');setTimeout(function(){location.href=roleTarget(role)},650)})}
  function initRegister(){var form=$('registerForm');if(!form)return;var msg=$('registerMessage');document.querySelectorAll('[data-role-tab]').forEach(function(btn){btn.addEventListener('click',function(){setRole(btn.dataset.roleTab)})});setRole('student');form.addEventListener('submit',function(e){e.preventDefault();var role=$('registerRole').value;var first=$('firstName').value.trim();var last=$('lastName').value.trim();var parentEmail=$('parentEmail').value.trim();var email=$('adultEmail').value.trim();var pass=$('adultPassword').value;if(!first||!last){show(msg,'error','Ad ve soyad alanlarını doldurun.');return}if(role==='student'){if(!isEmail(parentEmail)){show(msg,'error','Veli e-posta adresini doğru yazın.');return}localStorage.setItem('ekursPendingStudent',JSON.stringify({first:first,last:last,parentEmail:parentEmail,role:role,createdAt:new Date().toISOString()}));show(msg,'success','Öğrenci ön başvurusu alındı. Veli/öğretmen onayı sonrası giriş bilgileri oluşturulacak.');return}if(!isEmail(email)||pass.length<6){show(msg,'error','E-posta doğru olmalı ve şifre en az 6 karakter olmalı.');return}localStorage.setItem('ekursDemoUser',JSON.stringify({first:first,last:last,email:email,role:role,createdAt:new Date().toISOString()}));show(msg,'success','Hesap oluşturuldu. Paneline yönlendiriliyorsun.');setTimeout(function(){location.href=roleTarget(role)},750)})}
  function initReset(){var form=$('resetForm');if(!form)return;var msg=$('resetMessage');form.addEventListener('submit',function(e){e.preventDefault();var email=$('resetEmail').value.trim();if(!isEmail(email)){show(msg,'error','E-posta adresini doğru yazın.');return}show(msg,'success','Şifre sıfırlama bağlantısı gönderildi. Gelen kutunu kontrol edin.')})}
  initLogin();initRegister();initReset();
})();
