(function(){
  'use strict';
  var notes={"Türkçe":"Okuma, yazma, anlama ve dil becerileri.","Türk Dili ve Edebiyatı":"Metin, edebiyat, anlatım ve sınav becerileri.","Matematik":"MEB tema akışı, kazanım temelli pratik ve testler.","Hayat Bilgisi":"Okul, aile, çevre, sağlık ve güvenli yaşam.","Fen Bilimleri":"Deney, gözlem, bilimsel düşünme ve konu testleri.","Sosyal Bilgiler":"Tarih, coğrafya, yurttaşlık ve günlük yaşam bağlantıları.","İngilizce":"Kelime, dinleme, okuma ve temel iletişim.","Din Kültürü ve Ahlak Bilgisi":"Değerler, ahlak ve temel din kültürü konuları.","T.C. İnkılap Tarihi ve Atatürkçülük":"Kronoloji, kavramlar ve LGS odaklı soru analizi.","Fizik":"Kavram, problem çözme ve deney temelli öğrenme.","Kimya":"Madde, değişim, işlem ve laboratuvar mantığı.","Biyoloji":"Canlılar, sistemler ve bilimsel süreçler.","Tarih":"Kronoloji, neden-sonuç ve kaynak okuma.","Coğrafya":"Harita, çevre, insan ve mekân ilişkileri.","Felsefe":"Kavram, akıl yürütme ve düşünme becerileri."};
  var colors={"Türkçe":"red-500","Türk Dili ve Edebiyatı":"rose-500","Matematik":"blue-500","Hayat Bilgisi":"green-400","Fen Bilimleri":"teal-500","Sosyal Bilgiler":"amber-500","İngilizce":"purple-500","Din Kültürü ve Ahlak Bilgisi":"emerald-500","T.C. İnkılap Tarihi ve Atatürkçülük":"red-600","Fizik":"sky-500","Kimya":"violet-500","Biyoloji":"green-500","Tarih":"amber-600","Coğrafya":"cyan-600","Felsefe":"indigo-500"};
  var subjectRows={
    1:['Türkçe','Matematik','Hayat Bilgisi'],
    2:['Türkçe','Matematik','Hayat Bilgisi','İngilizce'],
    3:['Türkçe','Matematik','Hayat Bilgisi','Fen Bilimleri','İngilizce'],
    4:['Türkçe','Matematik','Fen Bilimleri','Sosyal Bilgiler','İngilizce','Din Kültürü ve Ahlak Bilgisi'],
    5:['Türkçe','Matematik','Fen Bilimleri','Sosyal Bilgiler','İngilizce','Din Kültürü ve Ahlak Bilgisi'],
    6:['Türkçe','Matematik','Fen Bilimleri','Sosyal Bilgiler','İngilizce','Din Kültürü ve Ahlak Bilgisi'],
    7:['Türkçe','Matematik','Fen Bilimleri','Sosyal Bilgiler','İngilizce','Din Kültürü ve Ahlak Bilgisi'],
    8:['Türkçe','Matematik','Fen Bilimleri','T.C. İnkılap Tarihi ve Atatürkçülük','İngilizce','Din Kültürü ve Ahlak Bilgisi'],
    9:['Türk Dili ve Edebiyatı','Matematik','Fizik','Kimya','Biyoloji','Tarih','Coğrafya','Felsefe','İngilizce','Din Kültürü ve Ahlak Bilgisi'],
    10:['Türk Dili ve Edebiyatı','Matematik','Fizik','Kimya','Biyoloji','Tarih','Coğrafya','Felsefe','İngilizce','Din Kültürü ve Ahlak Bilgisi'],
    11:['Türk Dili ve Edebiyatı','Matematik','Fizik','Kimya','Biyoloji','Tarih','Coğrafya','Felsefe','İngilizce','Din Kültürü ve Ahlak Bilgisi'],
    12:['Türk Dili ve Edebiyatı','Matematik','Fizik','Kimya','Biyoloji','Tarih','Coğrafya','Felsefe','İngilizce','Din Kültürü ve Ahlak Bilgisi']
  };
  function tier(grade){return grade<=4?'PRIMARY':grade<=8?'MIDDLE':'HIGH';}
  function tierLabel(t){return t==='PRIMARY'?'İlkokul':t==='MIDDLE'?'Ortaokul':'Lise';}
  function slug(text){return text.toLocaleLowerCase('tr-TR').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ı/g,'i').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
  function initial(name){return name.split(' ').filter(Boolean).slice(0,2).map(function(w){return w.charAt(0);}).join('');}
  function route(grade,subject){return '/siniflar/'+grade+'-sinif/'+slug(subject)+'.html';}
  function htmlRoute(grade,subject){return subject==='Matematik'?'/siniflar/'+grade+'-sinif/matematik.html':route(grade,subject);}
  function testHref(grade,subject){return grade===2?'/testler/2-sinif.html':'/testler/index.html?sinif='+grade+'&ders='+slug(subject);}
  function buildMap(){return Object.keys(subjectRows).map(function(key){var grade=Number(key),t=tier(grade);return{grade:grade,gradeName:grade+'. Sınıf',tier:t,tierSettings:{theme:t==='PRIMARY'?'playful':t==='MIDDLE'?'clean-engaging':'minimal-data-dense',hasVoiceAssist:t==='PRIMARY',hasAvatarGuide:t==='PRIMARY',hasPositiveReinforcement:t!=='HIGH',hasProgressRings:t!=='PRIMARY',hasStreaks:t!=='PRIMARY',hasClassLeaderboard:t==='MIDDLE',hasDarkMode:t==='HIGH',hasPomodoro:t==='HIGH',examMode:grade===8?'LGS_FOCUS':t==='MIDDLE'?'LGS_AWARENESS':t==='HIGH'?'YKS_ANALYTICS':null},subjects:subjectRows[grade].map(function(name){return{slug:slug(name),name:name,themeColor:colors[name]||'blue-500',hasVoiceAssist:t==='PRIMARY',isExamFocus:grade>=8,route:route(grade,name)};})};});}
  var curriculum=buildMap();
  function getGradeData(grade){return curriculum.find(function(item){return item.grade===grade;});}
  function mapText(grade,cfg){if(cfg.tier==='HIGH'){return 'Sınav Rotası\nKonu haritası • Zayıf alan analizi • Test pratiği\nYKS odaklı dersler ve çalışma araçları tek ekranda.';} if(cfg.tier==='MIDDLE'){return 'Çalışma Rotası\nDersler • Kazanımlar • Testler • LGS hazırlık alışkanlığı\nHer karttan derse veya teste geç.';} return 'Öğrenme Macerası\nDersler • Görseller • Sesli destek • Günlük küçük hedefler\n2. sınıf matematik sayfasındaki gibi kartlı ve kolay seçim.';}
  function insertAfter(node,html){if(!node){return;} var wrap=document.createElement('div');wrap.innerHTML=html.trim();node.parentNode.insertBefore(wrap.firstElementChild,node.nextSibling);}
  function enhanceLayout(grade,cfg){var hero=document.querySelector('.class-hero');if(hero&&!document.querySelector('.class-stat-section')){insertAfter(hero,'<section class="class-stat-section"><div class="class-container"><div class="class-stat-grid"><div class="class-top-stat"><strong>'+cfg.subjects.length+'</strong><small>MEB dersi</small></div><div class="class-top-stat"><strong>'+cfg.tier+'</strong><small>Pedagojik katman</small></div><div class="class-top-stat"><strong>'+(cfg.tierSettings.hasVoiceAssist?'Var':'Yok')+'</strong><small>Sesli destek</small></div><div class="class-top-stat"><strong>'+((cfg.tierSettings.examMode)||'Temel')+'</strong><small>Mod</small></div></div><div class="class-adventure-map">'+mapText(grade,cfg).replace(/\n/g,'<br>')+'</div></div></section>');}
    var stat=document.querySelector('.class-stat-section');if(stat&&!document.querySelector('.class-grade-section')){var links='';for(var i=1;i<=12;i++){links+='<a '+(i===grade?'class="active" ':'')+'href="/siniflar/'+i+'-sinif/index.html">'+i+'. sınıf</a>';} insertAfter(stat,'<section class="class-grade-section"><div class="class-container class-grade-strip">'+links+'</div></section>');}
    var grid=document.getElementById('lessonGrid');if(grid&&!document.querySelector('.class-guide-cards')){grid.insertAdjacentHTML('beforebegin','<div class="class-guide-cards"><a class="class-guide-card" href="/siniflar/'+grade+'-sinif/matematik.html"><span>Bugünkü öneri</span><strong>Matematik temalarıyla başla</strong><small>MEB tema akışı ve yaş grubuna uygun arayüz hazır.</small></a><a class="class-guide-card" href="/data/meb-curriculum-map.json"><span>Veri haritası</span><strong>JSON müfredat tohumu hazır</strong><small>Tier, renk, sesli destek ve sınav odağı bu dosyada tutulur.</small></a><a class="class-guide-card" href="/ogrenci/panel.html"><span>Takip</span><strong>Öğrenci paneliyle ilerle</strong><small>Hedef, yanlışlar ve başarı alanları aynı sistemde izlenir.</small></a></div>');}}
  function render(){var body=document.body,grade=parseInt(body.getAttribute('data-grade'),10),cfg=getGradeData(grade);if(!cfg){return;} body.classList.add('tier-'+cfg.tier.toLowerCase());var label=tierLabel(cfg.tier);var title=document.querySelector('[data-class-title]');if(title){title.textContent=cfg.gradeName+' dersleri ve testleri';}var badge=document.querySelector('[data-class-badge]');if(badge){badge.textContent=label+' · MEB çekirdek ders haritası';}var lead=document.querySelector('[data-class-lead]');if(lead){lead.textContent=cfg.gradeName+' için '+cfg.tier+' arayüz katmanına bağlı MEB dersleri ve test yolları.';}var count=document.querySelector('[data-lesson-count]');if(count){count.textContent=cfg.subjects.length;}var tierEl=document.querySelector('[data-tier-label]');if(tierEl){tierEl.textContent=label;}enhanceLayout(grade,cfg);var grid=document.getElementById('lessonGrid');if(grid){grid.innerHTML=cfg.subjects.map(function(s){var kind=cfg.tier==='HIGH'?'YKS odaklı':grade===8?'LGS odaklı':cfg.tier==='MIDDLE'?'Kazanım':'Sesli destek';return '<article class="lesson-card" data-subject="'+s.slug+'" data-color="'+s.themeColor+'"><div class="lesson-top"><span class="lesson-icon">'+initial(s.name)+'</span><span class="lesson-kind">'+kind+'</span></div><h3>'+s.name+'</h3><p>'+((notes[s.name])||'MEB ders akışına uygun konu ve test çalışmaları.')+'</p><div class="lesson-tags"><span>'+cfg.gradeName+'</span><span>'+cfg.tier+'</span><span>'+s.themeColor+'</span>'+(s.hasVoiceAssist?'<span>Sesli</span>':'')+(s.isExamFocus?'<span>Sınav</span>':'')+'</div><div class="lesson-actions"><a class="class-btn primary" href="'+htmlRoute(grade,s.name)+'">Dersi Aç</a><a class="class-btn soft" href="'+testHref(grade,s.name)+'">Testlere Git</a></div></article>';}).join('');}
    var quick=document.getElementById('quickClassLinks');if(quick){quick.innerHTML='<a class="class-btn primary" href="/siniflar/'+grade+'-sinif/matematik.html">Matematik Temalarını Aç</a><a class="class-btn light" href="/data/meb-curriculum-map.json">JSON Haritayı Aç</a><a class="class-btn light" href="/siniflar/index.html">Tüm Sınıflar</a>';}}
  window.EKursMebCurriculumMap=curriculum;window.EKursClassLessons={data:curriculum,getGradeData:getGradeData,getGradeTier:tier};
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',render);}else{render();}
})();
