(function(){
  'use strict';
  var lessonNotes={"Türkçe":"Okuma, yazma, anlama ve dil becerileri.","Türk Dili ve Edebiyatı":"Metin, edebiyat, anlatım ve sınav becerileri.","Matematik":"MEB tema akışı, kazanım temelli pratik ve testler.","Hayat Bilgisi":"Okul, aile, çevre, sağlık ve güvenli yaşam.","Fen Bilimleri":"Deney, gözlem, bilimsel düşünme ve konu testleri.","Sosyal Bilgiler":"Tarih, coğrafya, yurttaşlık ve günlük yaşam bağlantıları.","Din Kültürü ve Ahlak Bilgisi":"Değerler, ahlak ve temel din kültürü konuları.","Yabancı Dil":"Kelime, dinleme, okuma ve temel iletişim.","Birinci Yabancı Dil":"Okuma, yazma, dinleme ve sınav odaklı pratik.","T.C. İnkılap Tarihi ve Atatürkçülük":"Kronoloji, kavramlar ve soru analizi.","Görsel Sanatlar":"Sanat, üretim ve görsel okuryazarlık etkinlikleri.","Müzik":"Ritim, dinleme ve müzik kültürü çalışmaları.","Beden Eğitimi ve Oyun":"Hareket, oyun ve sağlıklı yaşam etkinlikleri.","Beden Eğitimi ve Spor":"Spor, sağlık ve hareket becerileri.","Bilişim Teknolojileri ve Yazılım":"Dijital beceriler, algoritma ve güvenli teknoloji kullanımı.","Teknoloji ve Tasarım":"Tasarım düşüncesi, ürün geliştirme ve proje çalışmaları.","Trafik Güvenliği":"Güvenli ulaşım ve günlük yaşam kuralları.","İnsan Hakları, Yurttaşlık ve Demokrasi":"Hak, sorumluluk ve demokratik yaşam becerileri.","Rehberlik ve Kariyer Planlama":"Hedef belirleme, öğrenme alışkanlığı ve kariyer farkındalığı.","Fizik":"Kavram, problem çözme ve deney temelli öğrenme.","Kimya":"Madde, değişim, işlem ve laboratuvar mantığı.","Biyoloji":"Canlılar, sistemler ve bilimsel süreçler.","Tarih":"Kronoloji, neden-sonuç ve kaynak okuma.","Coğrafya":"Harita, çevre, insan ve mekân ilişkileri.","Felsefe":"Kavram, akıl yürütme ve düşünme becerileri.","Sağlık Bilgisi ve Trafik Kültürü":"Sağlıklı yaşam ve güvenli trafik kültürü.","Görsel Sanatlar/Müzik":"Sanat ve müzik alanı çalışmaları."};
  var data={
    1:{level:'İlkokul',tier:'primary',headline:'MEB ilkokul 1. sınıf dersleri',lessons:[['Türkçe','Zorunlu'],['Matematik','Zorunlu'],['Hayat Bilgisi','Zorunlu'],['Görsel Sanatlar','Zorunlu'],['Müzik','Zorunlu'],['Beden Eğitimi ve Oyun','Zorunlu']]},
    2:{level:'İlkokul',tier:'primary',headline:'MEB ilkokul 2. sınıf dersleri',lessons:[['Türkçe','Zorunlu'],['Matematik','Zorunlu'],['Hayat Bilgisi','Zorunlu'],['Yabancı Dil','Zorunlu'],['Görsel Sanatlar','Zorunlu'],['Müzik','Zorunlu'],['Beden Eğitimi ve Oyun','Zorunlu']]},
    3:{level:'İlkokul',tier:'primary',headline:'MEB ilkokul 3. sınıf dersleri',lessons:[['Türkçe','Zorunlu'],['Matematik','Zorunlu'],['Hayat Bilgisi','Zorunlu'],['Fen Bilimleri','Zorunlu'],['Yabancı Dil','Zorunlu'],['Görsel Sanatlar','Zorunlu'],['Müzik','Zorunlu'],['Beden Eğitimi ve Oyun','Zorunlu']]},
    4:{level:'İlkokul',tier:'primary',headline:'MEB ilkokul 4. sınıf dersleri',lessons:[['Türkçe','Zorunlu'],['Matematik','Zorunlu'],['Fen Bilimleri','Zorunlu'],['Sosyal Bilgiler','Zorunlu'],['Din Kültürü ve Ahlak Bilgisi','Zorunlu'],['Yabancı Dil','Zorunlu'],['Görsel Sanatlar','Zorunlu'],['Müzik','Zorunlu'],['Beden Eğitimi ve Oyun','Zorunlu'],['Trafik Güvenliği','Zorunlu'],['İnsan Hakları, Yurttaşlık ve Demokrasi','Zorunlu']]},
    5:{level:'Ortaokul',tier:'middle',headline:'MEB ortaokul 5. sınıf dersleri',lessons:[['Türkçe','Zorunlu'],['Matematik','Zorunlu'],['Fen Bilimleri','Zorunlu'],['Sosyal Bilgiler','Zorunlu'],['Din Kültürü ve Ahlak Bilgisi','Zorunlu'],['Yabancı Dil','Zorunlu'],['Görsel Sanatlar','Zorunlu'],['Müzik','Zorunlu'],['Beden Eğitimi ve Spor','Zorunlu'],['Bilişim Teknolojileri ve Yazılım','Zorunlu']]},
    6:{level:'Ortaokul',tier:'middle',headline:'MEB ortaokul 6. sınıf dersleri',lessons:[['Türkçe','Zorunlu'],['Matematik','Zorunlu'],['Fen Bilimleri','Zorunlu'],['Sosyal Bilgiler','Zorunlu'],['Din Kültürü ve Ahlak Bilgisi','Zorunlu'],['Yabancı Dil','Zorunlu'],['Görsel Sanatlar','Zorunlu'],['Müzik','Zorunlu'],['Beden Eğitimi ve Spor','Zorunlu'],['Bilişim Teknolojileri ve Yazılım','Zorunlu']]},
    7:{level:'Ortaokul',tier:'middle',headline:'MEB ortaokul 7. sınıf dersleri',lessons:[['Türkçe','Zorunlu'],['Matematik','Zorunlu'],['Fen Bilimleri','Zorunlu'],['Sosyal Bilgiler','Zorunlu'],['Din Kültürü ve Ahlak Bilgisi','Zorunlu'],['Yabancı Dil','Zorunlu'],['Görsel Sanatlar','Zorunlu'],['Müzik','Zorunlu'],['Beden Eğitimi ve Spor','Zorunlu'],['Teknoloji ve Tasarım','Zorunlu']]},
    8:{level:'Ortaokul',tier:'middle',headline:'MEB ortaokul 8. sınıf dersleri',lessons:[['Türkçe','Zorunlu'],['Matematik','Zorunlu'],['Fen Bilimleri','Zorunlu'],['T.C. İnkılap Tarihi ve Atatürkçülük','Zorunlu'],['Din Kültürü ve Ahlak Bilgisi','Zorunlu'],['Yabancı Dil','Zorunlu'],['Görsel Sanatlar','Zorunlu'],['Müzik','Zorunlu'],['Beden Eğitimi ve Spor','Zorunlu'],['Teknoloji ve Tasarım','Zorunlu'],['Rehberlik ve Kariyer Planlama','Zorunlu']]},
    9:{level:'Lise',tier:'high',headline:'MEB ortaöğretim 9. sınıf dersleri',lessons:[['Türk Dili ve Edebiyatı','Ortak'],['Matematik','Ortak'],['Fizik','Ortak'],['Kimya','Ortak'],['Biyoloji','Ortak'],['Tarih','Ortak'],['Coğrafya','Ortak'],['Din Kültürü ve Ahlak Bilgisi','Ortak'],['Birinci Yabancı Dil','Ortak'],['Beden Eğitimi ve Spor','Ortak'],['Görsel Sanatlar/Müzik','Ortak'],['Sağlık Bilgisi ve Trafik Kültürü','Ortak']]},
    10:{level:'Lise',tier:'high',headline:'MEB ortaöğretim 10. sınıf dersleri',lessons:[['Türk Dili ve Edebiyatı','Ortak'],['Matematik','Ortak'],['Fizik','Ortak'],['Kimya','Ortak'],['Biyoloji','Ortak'],['Tarih','Ortak'],['Coğrafya','Ortak'],['Felsefe','Ortak'],['Din Kültürü ve Ahlak Bilgisi','Ortak'],['Birinci Yabancı Dil','Ortak'],['Beden Eğitimi ve Spor','Ortak'],['Görsel Sanatlar/Müzik','Ortak']]},
    11:{level:'Lise',tier:'high',headline:'MEB ortaöğretim 11. sınıf dersleri',lessons:[['Türk Dili ve Edebiyatı','Ortak'],['Matematik','Alan/Seçmeli'],['Fizik','Alan/Seçmeli'],['Kimya','Alan/Seçmeli'],['Biyoloji','Alan/Seçmeli'],['Tarih','Alan/Seçmeli'],['Coğrafya','Alan/Seçmeli'],['Felsefe','Ortak'],['Din Kültürü ve Ahlak Bilgisi','Ortak'],['Birinci Yabancı Dil','Ortak'],['Beden Eğitimi ve Spor','Ortak'],['Görsel Sanatlar/Müzik','Ortak']]},
    12:{level:'Lise',tier:'high',headline:'MEB ortaöğretim 12. sınıf dersleri',lessons:[['Türk Dili ve Edebiyatı','Ortak'],['Matematik','Alan/Seçmeli'],['Fizik','Alan/Seçmeli'],['Kimya','Alan/Seçmeli'],['Biyoloji','Alan/Seçmeli'],['T.C. İnkılap Tarihi ve Atatürkçülük','Ortak'],['Coğrafya','Alan/Seçmeli'],['Felsefe','Ortak'],['Din Kültürü ve Ahlak Bilgisi','Ortak'],['Birinci Yabancı Dil','Ortak'],['Beden Eğitimi ve Spor','Ortak'],['Görsel Sanatlar/Müzik','Ortak']]}
  };
  function slug(text){return text.toLocaleLowerCase('tr-TR').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ı/g,'i').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
  function initial(name){return name.split(' ').filter(Boolean).slice(0,2).map(function(w){return w.charAt(0);}).join('');}
  function href(grade,name){if(name==='Matematik'){return '/siniflar/'+grade+'-sinif/matematik.html';} if(name==='Türkçe'||name==='Türk Dili ve Edebiyatı'){return '/dersler/turkce/index.html';} if(name==='Hayat Bilgisi'){return '/dersler/hayat-bilgisi/index.html';} return '/dersler/index.html?ders='+slug(name)+'&sinif='+grade;}
  function testHref(grade,name){if(grade===2){return '/testler/2-sinif.html';} return '/testler/index.html?sinif='+grade+'&ders='+slug(name);}
  function render(){var body=document.body;var grade=parseInt(body.getAttribute('data-grade'),10);var cfg=data[grade];if(!cfg){return;} body.classList.add('tier-'+cfg.tier);var title=document.querySelector('[data-class-title]');if(title){title.textContent=grade+'. sınıf dersleri ve testleri';} var badge=document.querySelector('[data-class-badge]');if(badge){badge.textContent=cfg.level+' · MEB ders listesi';} var lead=document.querySelector('[data-class-lead]');if(lead){lead.textContent=cfg.headline+' ve seviyeye uygun test yolları tek sayfada toplandı.';} var count=document.querySelector('[data-lesson-count]');if(count){count.textContent=cfg.lessons.length;} var tier=document.querySelector('[data-tier-label]');if(tier){tier.textContent=cfg.level;} var grid=document.getElementById('lessonGrid');if(grid){grid.innerHTML=cfg.lessons.map(function(item){var name=item[0],kind=item[1],note=lessonNotes[name]||'MEB ders akışına uygun konu ve test çalışmaları.';return '<article class="lesson-card"><div class="lesson-top"><span class="lesson-icon">'+initial(name)+'</span><span class="lesson-kind">'+kind+'</span></div><h3>'+name+'</h3><p>'+note+'</p><div class="lesson-tags"><span>'+grade+'. sınıf</span><span>'+cfg.level+'</span><span>MEB</span></div><div class="lesson-actions"><a class="class-btn primary" href="'+href(grade,name)+'">Dersi Aç</a><a class="class-btn soft" href="'+testHref(grade,name)+'">Testlere Git</a></div></article>';}).join('');}
    var quick=document.getElementById('quickClassLinks');if(quick){quick.innerHTML='<a class="class-btn primary" href="/siniflar/'+grade+'-sinif/matematik.html">Matematik Temalarını Aç</a><a class="class-btn light" href="/testler/index.html?sinif='+grade+'">'+grade+'. Sınıf Testleri</a><a class="class-btn light" href="/siniflar/index.html">Tüm Sınıflar</a>';}
  }
  window.EKursClassLessons={data:data,getGradeData:function(grade){return data[grade];}};
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',render);}else{render();}
})();