(function(){
  'use strict';
  function loadData(done){if(window.mufredatData){done();return;}var s=document.createElement('script');s.src='/assets/js/mufredat-data.js';s.onload=done;document.head.appendChild(s);}
  function tierLabel(t){return t==='PRIMARY'?'İlkokul':t==='MIDDLE'?'Ortaokul':'Lise';}
  function initial(name){return name.split(' ').filter(Boolean).slice(0,2).map(function(w){return w.charAt(0);}).join('');}
  function mapText(grade,data){if(data.tier==='HIGH'){return 'Sınav Rotası<br>Konu haritası • Zayıf alan analizi • Test pratiği<br>YKS odaklı ortak dersler tek ekranda.';} if(data.tier==='MIDDLE'){return 'Çalışma Rotası<br>Dersler • Kazanımlar • Testler • LGS hazırlık alışkanlığı<br>Her karttan derse veya teste geç.';} return 'Öğrenme Macerası<br>Dersler • Görseller • Sesli destek • Günlük küçük hedefler<br>2. sınıf matematik sayfasındaki gibi kartlı ve kolay seçim.';}
  function insertAfter(node,html){if(!node){return;}var wrap=document.createElement('div');wrap.innerHTML=html.trim();node.parentNode.insertBefore(wrap.firstElementChild,node.nextSibling);}
  function enhance(grade,data){var hero=document.querySelector('.class-hero');if(hero&&!document.querySelector('.class-stat-section')){var voice=data.tier==='PRIMARY'?'Var':'Yok';insertAfter(hero,'<section class="class-stat-section"><div class="class-container"><div class="class-stat-grid"><div class="class-top-stat"><strong>'+Object.keys(data.lessons).length+'</strong><small>MEB dersi</small></div><div class="class-top-stat"><strong>'+data.tier+'</strong><small>Pedagojik katman</small></div><div class="class-top-stat"><strong>'+voice+'</strong><small>Sesli destek</small></div><div class="class-top-stat"><strong>'+(data.tier==='HIGH'?'YKS':data.tier==='MIDDLE'?'LGS':'Temel')+'</strong><small>Mod</small></div></div><div class="class-adventure-map">'+mapText(grade,data)+'</div></div></section>');}
    var stat=document.querySelector('.class-stat-section');if(stat&&!document.querySelector('.class-grade-section')){var links='';for(var i=1;i<=12;i++){links+='<a '+(i===grade?'class="active" ':'')+'href="/siniflar/'+i+'-sinif/index.html">'+i+'. sınıf</a>';}insertAfter(stat,'<section class="class-grade-section"><div class="class-container class-grade-strip">'+links+'</div></section>');}
    var grid=document.getElementById('lessonGrid');if(grid&&!document.querySelector('.class-guide-cards')){grid.insertAdjacentHTML('beforebegin','<div class="class-guide-cards"><a class="class-guide-card" href="/siniflar/'+grade+'-sinif/matematik.html"><span>Bugünkü öneri</span><strong>Matematik temalarıyla başla</strong><small>MEB tema akışı ve yaş grubuna uygun arayüz hazır.</small></a><a class="class-guide-card" href="/assets/js/mufredat-data.js"><span>Veri haritası</span><strong>Sınıf-ders-ünite-konu verisi hazır</strong><small>Her ders en az 3 ünite ve 5 konu başlığıyla gelir.</small></a><a class="class-guide-card" href="/ogrenci/panel.html"><span>Takip</span><strong>Öğrenci paneliyle ilerle</strong><small>Hedef, yanlışlar ve başarı alanları aynı sistemde izlenir.</small></a></div>');}}
  function render(){var grade=parseInt(document.body.getAttribute('data-grade'),10);var key=grade+'-sinif';var data=window.mufredatData&&window.mufredatData[key];if(!data){return;}document.body.classList.add('tier-'+data.tier.toLowerCase());var label=tierLabel(data.tier);var lessons=Object.keys(data.lessons).map(function(slug){return data.lessons[slug];});var title=document.querySelector('[data-class-title]');if(title){title.textContent=data.title+' dersleri ve testleri';}var badge=document.querySelector('[data-class-badge]');if(badge){badge.textContent=label+' · MEB/TYMM ders haritası';}var lead=document.querySelector('[data-class-lead]');if(lead){lead.textContent=data.title+' için MEB uyumlu ders, tema, konu ve test yolları tek sayfada toplandı.';}var count=document.querySelector('[data-lesson-count]');if(count){count.textContent=lessons.length;}var tier=document.querySelector('[data-tier-label]');if(tier){tier.textContent=label;}enhance(grade,data);var grid=document.getElementById('lessonGrid');if(grid){grid.innerHTML=lessons.map(function(lesson){var kind=data.tier==='HIGH'?'YKS odaklı':grade===8?'LGS odaklı':data.tier==='MIDDLE'?'Kazanım':'Sesli destek';var route='/siniflar/'+key+'/'+lesson.slug+'.html';var test='/testler/index.html?sinif='+grade+'&ders='+lesson.slug;return '<article class="lesson-card"><div class="lesson-top"><span class="lesson-icon">'+initial(lesson.title)+'</span><span class="lesson-kind">'+kind+'</span></div><h3>'+lesson.title+'</h3><p>'+lesson.themes[0].description+'</p><div class="lesson-tags"><span>'+data.title+'</span><span>'+data.tier+'</span><span>'+lesson.themes.length+' ünite</span></div><div class="lesson-actions"><a class="class-btn primary" href="'+route+'">Dersi Aç</a><a class="class-btn soft" href="'+test+'">Testlere Git</a></div></article>';}).join('');}
    var quick=document.getElementById('quickClassLinks');if(quick){quick.innerHTML='<a class="class-btn primary" href="/siniflar/'+key+'/matematik.html">Matematik Temalarını Aç</a><a class="class-btn light" href="/assets/js/mufredat-data.js">Müfredat Verisi</a><a class="class-btn light" href="/siniflar/index.html">Tüm Sınıflar</a>';}}
  loadData(function(){if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',render);}else{render();}});
})();
