(function(){
  'use strict';
  var grade='2. Sınıf';
  var base='/siniflar/2-sinif';
  var subjects={
    turkce:{name:'Türkçe',desc:'Okuma, anlama, yazma, dil bilgisi, dinleme ve konuşma çalışmaları.',actions:['Konu Anlatımı','Etkinlik','Test Çöz','Okuma Metni'],themes:[
      ['Okuma ve Anlama',['Kısa Metin Okuma','Okuduğunu Anlama','Metnin Konusu','Metnin Ana Fikri','Görselden Anlam Çıkarma']],
      ['Yazma Becerileri',['Cümle Yazma','Noktalama İşaretleri','Büyük Harf Kullanımı','Kısa Metin Yazma','Duygu ve Düşüncelerini Yazma']],
      ['Dil Bilgisi',['Kelime Bilgisi','Eş Anlamlı Kelimeler','Zıt Anlamlı Kelimeler','Hece Bilgisi','Cümle Bilgisi']],
      ['Dinleme ve Konuşma',['Dinlediğini Anlama','Soru Sorma','Cevap Verme','Kendini İfade Etme','Görsel Sunum']]
    ]},
    matematik:{name:'Matematik',desc:'MEB uyumlu tema, konu anlatımı, alıştırma, örnek soru ve test akışı.',actions:['Konu Anlatımı','Alıştırma','Test Çöz','Örnek Sorular','Yanlışları Tekrar Çöz'],themes:[
      ['Sayılar ve Nicelikler',['Doğal Sayılar','Sayıları Okuma ve Yazma','Basamak Değeri','Sayıları Karşılaştırma','Sayıları Sıralama','Ritmik Sayma','Sayı Örüntüleri','Tahmin Etme']],
      ['İşlemlerden Cebirsel Düşünmeye',['Toplama İşlemi','Eldeli Toplama','Çıkarma İşlemi','Onluk Bozarak Çıkarma','Toplama ve Çıkarma Problemleri','Çarpma İşlemine Hazırlık','Bölme İşlemine Hazırlık','Eşitlik']],
      ['Nesnelerin Geometrisi',['Geometrik Şekiller','Kare, Dikdörtgen, Üçgen ve Çember','Geometrik Cisimler','Küp, Prizma, Silindir ve Küre','Kenar, Köşe ve Yüz','Simetri','Yer ve Yön Bulma']],
      ['Ölçme',['Uzunluk Ölçme','Metre ve Santimetre','Zaman Ölçme','Saat Okuma','Para Tanıma','Paralarımızla İşlem','Kütle Ölçme','Sıvı Ölçme']],
      ['Veriye Dayalı Araştırma',['Veri Toplama','Tablo Oluşturma','Şekil Grafiği','Nesne Grafiği','Grafik Okuma','Grafik Yorumlama']]
    ]},
    'hayat-bilgisi':{name:'Hayat Bilgisi',desc:'Okul, ev, sağlık, güvenlik, ülkemiz ve doğa temelli yaşam becerileri.',actions:['Konu Anlatımı','Etkinlik','Test Çöz'],themes:[
      ['Okulumuzda Hayat',['Okul Kuralları','Sınıf Kuralları','Arkadaşlık İlişkileri','Okulda Yardımlaşma','Okulda Güvenlik']],
      ['Evimizde Hayat',['Aile Bireyleri','Evde Sorumluluklar','Evde Güvenlik','Aile İçi Yardımlaşma','Planlı Yaşam']],
      ['Sağlıklı Hayat',['Kişisel Temizlik','Sağlıklı Beslenme','Spor ve Hareket','Dinlenme','Hastalıklardan Korunma']],
      ['Güvenli Hayat',['Trafik Kuralları','Acil Durumlar','Güvenli Oyun Alanları','Yabancılarla İletişim','Afetlere Hazırlık']],
      ['Ülkemizde Hayat',['Bayrağımız','Milli Bayramlarımız','Atatürk','Kültürel Değerlerimiz','Yakın Çevremiz']],
      ['Doğada Hayat',['Bitkiler','Hayvanlar','Mevsimler','Doğayı Koruma','Geri Dönüşüm']]
    ]},
    ingilizce:{name:'İngilizce',desc:'2. sınıf düzeyinde kelime, dinleme, eşleştirme ve kısa diyalog çalışmaları.',actions:['Learn','Practice','Test','Listen'],themes:[
      ['Words',['Greetings','Classroom Language','Numbers','Colors','Objects']],
      ['Friends',['Introducing Yourself','Asking Names','Feelings','Simple Dialogues']],
      ['In the Classroom',['School Objects','Commands','Listening Activities','Matching Words']],
      ['Numbers and Colors',['Numbers 1-20','Colors','Count and Color','Listen and Choose']]
    ]},
    'gorsel-sanatlar':{name:'Görsel Sanatlar',desc:'Renk, çizgi, şekil, boyama ve görsel inceleme etkinlikleri.',actions:['Etkinliği Aç','Örnek Görsel','Boyama Sayfası'],themes:[['Görsel Sanatlar Etkinlikleri',['Renkleri Kullanma','Çizgi ve Şekil','Boyama Çalışmaları','Doğa Resmi','Hayal Gücüyle Resim','Görseli İnceleme']]]},
    muzik:{name:'Müzik',desc:'Sesleri ayırt etme, ritim, şarkı, dinleme ve basit çalgı etkinlikleri.',actions:['Etkinliği Aç','Şarkıyı Dinle','Ritim Çalış'],themes:[['Müzik Etkinlikleri',['Sesleri Ayırt Etme','Ritim Çalışmaları','Şarkılar','Dinleme Etkinlikleri','Müzikli Oyunlar','Basit Çalgılar']]]},
    'beden-egitimi-ve-oyun':{name:'Beden Eğitimi ve Oyun',desc:'Isınma, denge, koşma, top oyunları, grup oyunları ve güvenli hareket.',actions:['Etkinliği Aç','Oyun Kuralları','Güvenlik Uyarısı'],themes:[['Beden Eğitimi ve Oyun Etkinlikleri',['Isınma Hareketleri','Denge Oyunları','Koşma ve Zıplama','Top Oyunları','Grup Oyunları','Güvenli Hareket']]]}
  };
  function slug(s){return String(s).toLowerCase().replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
  function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function nav(){return '<header class="g1-header"><nav class="g1-nav g1-container"><a class="g1-logo" href="/index.html"><span class="g1-logo-mark">e</span><span>e-kurs.com</span></a><div class="g1-links"><a href="/index.html">Ana Sayfa</a><a href="/siniflar/index.html">Sınıflar</a><a href="/dersler/index.html">Dersler</a><a href="/testler/index.html">Testler</a><a class="g1-btn soft" href="/giris.html">Giriş Yap</a></div></nav></header>';}
  function footer(){return '<footer class="g1-footer"><div class="g1-container"><strong>e-kurs.com</strong><p>2. sınıf model öğrenme alanı. Ders, konu ve test butonları gerçek sayfalara açılır.</p></div></footer>';}
  function actionLink(subjectKey,topic,action){var topicSlug=slug(topic);if(action.indexOf('Test')>-1){return base+'/'+subjectKey+'/'+topicSlug+'-test.html';}if(action.indexOf('Yanlış')>-1){return base+'/'+subjectKey+'/'+topicSlug+'-test.html#yanlislar';}var anchor=action.indexOf('Okuma')>-1?'okuma-metni':action.indexOf('Etkin')>-1||action.indexOf('Alıştır')>-1||action.indexOf('Practice')>-1||action.indexOf('Listen')>-1||action.indexOf('Örnek')>-1||action.indexOf('Şark')>-1||action.indexOf('Ritim')>-1||action.indexOf('Kural')>-1||action.indexOf('Güvenlik')>-1||action.indexOf('Boyama')>-1?'etkinlik':'konu-anlatimi';return base+'/'+subjectKey+'/'+topicSlug+'.html#'+anchor;}
  function getParams(){var qs=new URLSearchParams(location.search);var path=location.pathname.split('/').filter(Boolean);var subject=document.body.dataset.subject||qs.get('ders')||path[2]||'matematik';var raw=document.body.dataset.topic||qs.get('konu')||path[3]||'dogal-sayilar';raw=raw.replace(/\.html$/,'').replace(/-test$/,'');return {subject:subject,topic:raw};}
  function titleFromSlug(subjectKey,topicSlug){var sub=subjects[subjectKey];if(!sub)return topicSlug;for(var i=0;i<sub.themes.length;i++){for(var j=0;j<sub.themes[i][1].length;j++){if(slug(sub.themes[i][1][j])===topicSlug)return sub.themes[i][1][j];}}return topicSlug.split('-').map(function(w){return w.charAt(0).toUpperCase()+w.slice(1);}).join(' ');}
  function renderSubject(){var key=document.body.dataset.subject;var sub=subjects[key];var app=document.getElementById('app');if(!app||!sub)return;var count=sub.themes.reduce(function(a,t){return a+t[1].length;},0);var themeHtml=sub.themes.map(function(theme,idx){return '<article class="g1-theme"><h3>'+(idx+1)+'. Tema: '+esc(theme[0])+'</h3><p>'+esc(sub.desc)+'</p><div class="g1-topic-list">'+theme[1].map(function(topic){return '<div class="g1-topic-row"><div class="g1-topic-title">'+esc(topic)+'</div><div class="g1-topic-actions">'+sub.actions.map(function(a){return '<a class="g1-btn '+(a.indexOf('Test')>-1?'green':'soft')+'" href="'+actionLink(key,topic,a)+'">'+esc(a)+'</a>';}).join('')+'</div></div>';}).join('')+'</div></article>';}).join('');app.innerHTML=nav()+'<main><section class="g1-hero"><div class="g1-container"><p class="g1-breadcrumb"><a href="/index.html">Ana Sayfa</a> / <a href="/siniflar/index.html">Sınıflar</a> / <a href="/siniflar/2-sinif/index.html">2. Sınıf</a> / '+esc(sub.name)+'</p><div class="g1-hero-grid"><div class="g1-hero-card"><span class="g1-kicker">2. Sınıf · Model sayfa</span><h1>2. Sınıf '+esc(sub.name)+'</h1><p class="g1-lead">'+esc(sub.desc)+' Her konu için ayrı konu ve test rotası hazır.</p><div class="g1-actions"><a class="g1-btn green" href="'+base+'/'+key+'/'+slug(sub.themes[0][1][0])+'-test.html">İlk Testi Aç</a><a class="g1-btn white" href="/siniflar/2-sinif/index.html">Sınıfa Dön</a></div></div><aside class="g1-panel"><div class="g1-mini-grid"><div class="g1-mini"><strong>'+sub.themes.length+'</strong><span>Tema</span></div><div class="g1-mini"><strong>'+count+'</strong><span>Konu</span></div><div class="g1-mini"><strong>Aktif</strong><span>Buton</span></div><div class="g1-mini"><strong>Mobil</strong><span>Uyumlu</span></div></div></aside></div></div></section><section class="g1-section"><div class="g1-container"><div class="g1-section-head"><div><h2>Tema ve Konular</h2><p class="g1-muted">Konu anlatımı, etkinlik, test ve dönüş bağlantıları hazır.</p></div></div>'+themeHtml+'</div></section></main>'+footer();}
  function renderTopic(){var p=getParams();var sub=subjects[p.subject];var app=document.getElementById('app');if(!app||!sub)return;var title=titleFromSlug(p.subject,p.topic);var testHref=base+'/'+p.subject+'/'+p.topic+'-test.html';app.innerHTML=nav()+'<main><section class="g1-hero"><div class="g1-container"><p class="g1-breadcrumb"><a href="/index.html">Ana Sayfa</a> / <a href="/siniflar/2-sinif/index.html">2. Sınıf</a> / <a href="'+base+'/'+p.subject+'.html">'+esc(sub.name)+'</a> / '+esc(title)+'</p><div class="g1-hero-card"><span class="g1-kicker">Konu Anlatımı</span><h1>'+esc(title)+'</h1><p class="g1-lead">Kısa anlatım, üç örnek, etkinlik alanı ve teste geçiş hazır. Bu sayfa boş değildir.</p><div class="g1-actions"><a class="g1-btn green" href="'+testHref+'">Teste Başla</a><a class="g1-btn white" href="'+base+'/'+p.subject+'.html">Derse Dön</a><a class="g1-btn soft" href="/siniflar/2-sinif/index.html">Sınıfa Dön</a></div></div></div></section><section class="g1-section"><div class="g1-container"><article id="konu-anlatimi" class="g1-topic-card"><h2>Konu Anlatımı</h2><p>'+esc(title)+' konusunu önce temel kavramla tanı, sonra örnekleri çözerek pekiştir.</p></article><div class="g1-example-grid"><div class="g1-example"><strong>Örnek 1</strong><p>Konuya uygun görseli veya metni dikkatle incele.</p></div><div class="g1-example"><strong>Örnek 2</strong><p>Bilgiyi kendi cümlenle anlat ve doğru seçeneği bul.</p></div><div class="g1-example"><strong>Örnek 3</strong><p>Benzer bir soru çözerek öğrendiğini kontrol et.</p></div></div><article id="etkinlik" class="g1-topic-card"><h2>Etkinlik ve Örnek Sorular</h2><p>Defterine kısa çalışma yap, eşleştir, say, çiz veya cümle kur. Ardından testle devam et.</p></article><article id="okuma-metni" class="g1-topic-card"><h2>Okuma Metni</h2><p>Bu bölümde konuya uygun kısa metin veya dinleme yönergesi yer alır.</p></article><div class="g1-actions"><a class="g1-btn green" href="'+testHref+'">Teste Başla</a><a class="g1-btn white" href="'+base+'/'+p.subject+'.html">Derse Dön</a><a class="g1-btn soft" href="/siniflar/2-sinif/index.html">Sınıfa Dön</a></div></div></section></main>'+footer();}
  function init(){var mode=document.body.dataset.mode;if(mode==='subject')renderSubject();if(mode==='topic')renderTopic();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
