(function(){
  'use strict';
  var base='/siniflar/1-sinif';
  var subjects={
    turkce:{name:'Türkçe',icon:'T',desc:'Ses, harf, hece, kelime, cümle ve okuduğunu anlama çalışmaları.',actions:['Konu Anlatımı','Etkinlik','Test Çöz','Okuma Metni'],themes:[
      ['Okuma Yazmaya Hazırlık',['Çizgi Çalışmaları','Sesleri Tanıma','Harfleri Tanıma','Hece Oluşturma','Kelime Oluşturma']],
      ['İlk Okuma Yazma',['Seslerden Heceye','Hecelerden Kelimeye','Kelimelerden Cümleye','Kısa Metin Okuma','Okuduğunu Anlama']],
      ['Dinleme ve Konuşma',['Görsel Okuma','Dinlediğini Anlama','Kendini Tanıtma','Soru Sorma','Cevap Verme']]
    ]},
    matematik:{name:'Matematik',icon:'M',desc:'Rakamlar, sayılar, işlemler, geometri, ölçme ve veri çalışmaları.',actions:['Konu Anlatımı','Alıştırma','Test Çöz','Görsel Etkinlik'],themes:[
      ['Sayılar ve Nicelikler',['Rakamları Tanıma','1’den 20’ye Kadar Sayılar','Nesne Sayma','Sayıları Okuma ve Yazma','Sıra Bildiren Sayılar','Ritmik Sayma']],
      ['İşlemlerden Cebirsel Düşünmeye',['Toplama İşlemine Giriş','Çıkarma İşlemine Giriş','Toplama Problemleri','Çıkarma Problemleri','Eşitlik']],
      ['Nesnelerin Geometrisi',['Geometrik Şekiller','Üçgen, Kare, Dikdörtgen, Çember','Uzamsal İlişkiler','Yer, Yön, Konum','Örüntüler']],
      ['Ölçme ve Veri',['Uzunluk Karşılaştırma','Ağır Hafif','Zaman Kavramı','Para Tanıma','Tablo ve Grafiklere Hazırlık']]
    ]},
    'hayat-bilgisi':{name:'Hayat Bilgisi',icon:'H',desc:'Okul, aile, güvenlik, sağlık, çevre ve doğa temelli yaşam becerileri.',actions:['Konu Anlatımı','Etkinlik','Test Çöz'],themes:[
      ['Ben ve Okulum',['Kendimi Tanıyorum','Okulumu Tanıyorum','Sınıf Kuralları','Arkadaşlık','Okulda Güvenlik']],
      ['Ailem ve Evim',['Ailemi Tanıyorum','Evde Sorumluluklarım','Evde Güvenlik','Sağlıklı Yaşam','Kişisel Bakım']],
      ['Çevrem ve Doğa',['Yakın Çevrem','Hayvanlar ve Bitkiler','Mevsimler','Doğayı Koruyalım','Trafikte Güvenlik']]
    ]},
    'gorsel-sanatlar':{name:'Görsel Sanatlar',icon:'G',desc:'Renk, çizgi, şekil, boyama ve görsel inceleme etkinlikleri.',actions:['Etkinliği Aç','Örnek Görsel','Boyama Sayfası'],themes:[['Görsel Sanatlar Etkinlikleri',['Renkleri Tanıyalım','Çizgi ve Şekiller','Boyama Çalışmaları','Hayal Gücümle Resim','Görseli İnceleme']]]},
    muzik:{name:'Müzik',icon:'MZ',desc:'Ses, ritim, şarkı, dinleme ve müzikli oyun çalışmaları.',actions:['Etkinliği Aç','Şarkıyı Dinle','Ritim Çalış'],themes:[['Müzik Etkinlikleri',['Sesleri Tanıyalım','Ritim Çalışmaları','Şarkılar','Dinleme Etkinlikleri','Müzikli Oyunlar']]]},
    'beden-egitimi-ve-oyun':{name:'Beden Eğitimi ve Oyun',icon:'B',desc:'Güvenli hareket, oyun kuralları, denge, koşma ve grup oyunları.',actions:['Etkinliği Aç','Oyun Kuralları','Güvenlik Uyarısı'],themes:[['Beden Eğitimi ve Oyun Etkinlikleri',['Isınma Hareketleri','Denge Oyunları','Koşma ve Zıplama','Top Oyunları','Grup Oyunları']]]}
  };
  function slug(s){return String(s).toLowerCase().replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
  function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function nav(active){return '<header class="g1-header"><nav class="g1-nav g1-container"><a class="g1-logo" href="/index.html"><span class="g1-logo-mark">e</span><span>e-kurs.com</span></a><div class="g1-links"><a href="/index.html">Ana Sayfa</a><a href="/siniflar/index.html">Sınıflar</a><a href="/dersler/index.html">Dersler</a><a href="/testler/index.html">Testler</a><a class="g1-btn soft" href="/giris.html">Giriş Yap</a></div></nav></header>';}
  function footer(){return '<footer class="g1-footer"><div class="g1-container"><strong>e-kurs.com</strong><p>1. sınıf çocuk dostu öğrenme alanı. Büyük yazı, gerçek bağlantılar ve anlaşılır test akışı.</p></div></footer>';}
  function actionLink(subjectKey,topic,action){var topicSlug=slug(topic);if(action.indexOf('Test')>-1){return base+'/'+subjectKey+'/'+topicSlug+'-test.html';}var anchor=action.indexOf('Okuma')>-1?'okuma-metni':action.indexOf('Etkin')>-1||action.indexOf('Alıştır')>-1||action.indexOf('Görsel')>-1||action.indexOf('Şark')>-1||action.indexOf('Ritim')>-1||action.indexOf('Kural')>-1||action.indexOf('Güvenlik')>-1||action.indexOf('Boyama')>-1?'etkinlik':'konu-anlatimi';return base+'/'+subjectKey+'/'+topicSlug+'.html#'+anchor;}
  function getParams(){var qs=new URLSearchParams(location.search);var path=location.pathname.split('/').filter(Boolean);var subject=document.body.dataset.subject||qs.get('ders')||path[2]||'matematik';var raw=document.body.dataset.topic||qs.get('konu')||path[3]||'rakamlari-tanima';raw=raw.replace(/\.html$/,'').replace(/-test$/,'');return {subject:subject,topic:raw};}
  function titleFromSlug(subjectKey,topicSlug){var sub=subjects[subjectKey];if(!sub)return topicSlug;for(var i=0;i<sub.themes.length;i++){for(var j=0;j<sub.themes[i][1].length;j++){if(slug(sub.themes[i][1][j])===topicSlug)return sub.themes[i][1][j];}}return topicSlug.split('-').map(function(w){return w.charAt(0).toUpperCase()+w.slice(1);}).join(' ');}
  function renderSubject(){var key=document.body.dataset.subject;var sub=subjects[key];var app=document.getElementById('app');if(!app||!sub)return;var themeHtml=sub.themes.map(function(theme,idx){return '<article class="g1-theme"><h3>'+(idx+1)+'. Tema: '+esc(theme[0])+'</h3><p>'+esc(sub.desc)+'</p><div class="g1-topic-list">'+theme[1].map(function(topic){return '<div class="g1-topic-row"><div class="g1-topic-title">'+esc(topic)+'</div><div class="g1-topic-actions">'+sub.actions.map(function(a){return '<a class="g1-btn '+(a.indexOf('Test')>-1?'green':'soft')+'" href="'+actionLink(key,topic,a)+'">'+esc(a)+'</a>';}).join('')+'</div></div>';}).join('')+'</div></article>';}).join('');app.innerHTML=nav(key)+'<main><section class="g1-hero"><div class="g1-container"><p class="g1-breadcrumb"><a href="/index.html">Ana Sayfa</a> / <a href="/siniflar/index.html">Sınıflar</a> / <a href="/siniflar/1-sinif/index.html">1. Sınıf</a> / '+esc(sub.name)+'</p><div class="g1-hero-grid"><div class="g1-hero-card"><span class="g1-kicker">1. Sınıf · Çocuk dostu</span><h1>1. Sınıf '+esc(sub.name)+'</h1><p class="g1-lead">'+esc(sub.desc)+' Tüm butonlar gerçek konu veya test sayfasına açılır.</p><div class="g1-actions"><a class="g1-btn green" href="'+base+'/'+key+'/'+slug(sub.themes[0][1][0])+'-test.html">İlk Testi Aç</a><a class="g1-btn white" href="/siniflar/1-sinif/index.html">Sınıfa Dön</a></div></div><aside class="g1-panel"><div class="g1-mini-grid"><div class="g1-mini"><strong>'+sub.themes.length+'</strong><span>Tema</span></div><div class="g1-mini"><strong>'+sub.themes.reduce(function(a,t){return a+t[1].length;},0)+'</strong><span>Konu</span></div><div class="g1-mini"><strong>Büyük</strong><span>Buton</span></div><div class="g1-mini"><strong>Aktif</strong><span>Link</span></div></div></aside></div></div></section><section class="g1-section"><div class="g1-container"><div class="g1-section-head"><div><h2>Tema ve Konular</h2><p class="g1-muted">Konu anlatımı, etkinlik ve test bağlantıları hazır.</p></div></div>'+themeHtml+'</div></section></main>'+footer();}
  function renderTopic(){var p=getParams();var sub=subjects[p.subject];var app=document.getElementById('app');if(!app||!sub)return;var title=titleFromSlug(p.subject,p.topic);var testHref=base+'/'+p.subject+'/'+p.topic+'-test.html';app.innerHTML=nav(p.subject)+'<main><section class="g1-hero"><div class="g1-container"><p class="g1-breadcrumb"><a href="/index.html">Ana Sayfa</a> / <a href="/siniflar/1-sinif/index.html">1. Sınıf</a> / <a href="'+base+'/'+p.subject+'.html">'+esc(sub.name)+'</a> / '+esc(title)+'</p><div class="g1-hero-card"><span class="g1-kicker">Konu Anlatımı</span><h1>'+esc(title)+'</h1><p class="g1-lead">Bu sayfa 1. sınıf öğrencisi için kısa, görsel ve örnekli hazırlanmıştır. Bağlantılar boş değildir; test ve derse dönüş butonları çalışır.</p><div class="g1-actions"><a class="g1-btn green" href="'+testHref+'">Teste Başla</a><a class="g1-btn white" href="'+base+'/'+p.subject+'.html">Derse Dön</a><a class="g1-btn soft" href="/siniflar/1-sinif/index.html">Sınıfa Dön</a></div></div></div></section><section class="g1-section"><div class="g1-container"><article id="konu-anlatimi" class="g1-topic-card"><h2>Konu Anlatımı</h2><p>'+esc(title)+' konusunu önce gerçek hayattan örneklerle tanıyalım. Küçük adımlarla ilerle, sonra testte kendini dene.</p></article><div class="g1-example-grid"><div class="g1-example"><strong>Örnek 1</strong><p>Resme veya nesneye bak, ne gördüğünü söyle.</p></div><div class="g1-example"><strong>Örnek 2</strong><p>Birlikte say, eşleştir veya doğru seçeneği bul.</p></div><div class="g1-example"><strong>Örnek 3</strong><p>Kendi cümlenle anlat ve kısa etkinliği tamamla.</p></div></div><article id="etkinlik" class="g1-topic-card"><h2>Etkinlik</h2><p>Defterine küçük bir çizim yap, üç örnek yaz veya bir yetişkine anlatarak konuyu pekiştir.</p></article><article id="okuma-metni" class="g1-topic-card"><h2>Okuma Metni</h2><p>Bu bölümde konuya uygun kısa metin, görsel inceleme veya yönergeli etkinlik bulunur.</p></article><div class="g1-actions"><a class="g1-btn green" href="'+testHref+'">Teste Başla</a><a class="g1-btn white" href="'+base+'/'+p.subject+'.html">Derse Dön</a></div></div></section></main>'+footer();}
  function defaultQuestions(subjectKey,topicTitle){if(subjectKey==='matematik'&&slug(topicTitle)==='rakamlari-tanima'){return [
    ['Aşağıdakilerden hangisi 3 rakamıdır?',['2','3','5'],1,'3 rakamı üç nesneyi gösterir.'],['Kaç tane yıldız var? ★ ★ ★ ★',['3','4','5'],1,'Yıldızları sayalım: 1, 2, 3, 4.'],['1, 2, 3, __ sırada hangi sayı gelir?',['4','5','6'],0,'3’ten sonra 4 gelir.'],['Kaç parmak gösteriliyor? ✋',['4','5','6'],1,'Bir elde 5 parmak vardır.'],['0 rakamı neyi gösterir?',['Hiç yok','Bir tane','İki tane'],0,'0, hiç nesne olmadığını gösterir.'],['Hangisi 7 rakamıdır?',['1','7','9'],1,'7 rakamı yediyi gösterir.'],['2 elma daha 1 elma kaç elma eder?',['2','3','4'],1,'2 elmadan sonra 1 elma daha gelirse 3 olur.'],['5’ten önce hangi sayı gelir?',['4','6','7'],0,'Sayarken 4, 5 diye gideriz.'],['Kaç tane daire var? ● ● ●',['2','3','4'],1,'Daireleri sayalım: 1, 2, 3.'],['9 sayısından sonra hangi sayı gelir?',['8','10','11'],1,'9’dan sonra 10 gelir.']
  ];}var t=topicTitle;return [['Bu çalışma hangi konu içindir?',[t,'2. Sınıf','Boş sayfa'],0,'Bu test '+t+' konusuna bağlıdır.'],['Derse dönmek için hangi buton kullanılır?',['Derse Dön','Kapat','Boş bırak'],0,'Derse Dön butonu seni ders sayfasına götürür.'],['Teste başlamadan önce ne yapılır?',['Soruyu oku','Rastgele seç','Sayfadan çık'],0,'Önce soruyu dikkatlice okuruz.'],['Doğru cevap nasıl görünür?',['Yeşil','Siyah','Boş'],0,'Doğru cevap yeşil gösterilir.'],['Yanlış cevapta ne çıkar?',['Açıklama','Hiçbir şey','Boş ekran'],0,'Yanlışta açıklama paneli açılır.'],['1. sınıf sayfalarında butonlar nasıl olmalı?',['Büyük','Çok küçük','Gizli'],0,'Küçük yaş için büyük buton kullanılır.'],['Konu anlatımı ne işe yarar?',['Öğrenmeye','Kaybolmaya','Sayfayı kapatmaya'],0,'Konu anlatımı öğrenmeyi kolaylaştırır.'],['Etkinlik ne sağlar?',['Pekiştirme','Boşluk','Hata'],0,'Etkinlik konuyu pekiştirir.'],['Test sonunda ne görünür?',['Sonuç','Boş sayfa','Sadece başlık'],0,'Test sonunda doğru, yanlış ve puan görünür.'],['Çalışma bitince nereye dönebilirsin?',['Konuya veya derse','Boş linke','Yanlış yere'],0,'Konuya ve derse dönüş butonları hazırdır.']];}
  function renderTest(){var p=getParams();var sub=subjects[p.subject]||subjects.matematik;var title=titleFromSlug(p.subject,p.topic);var q=defaultQuestions(p.subject,title);var app=document.getElementById('app');if(!app)return;app.innerHTML=nav(p.subject)+'<main><section class="g1-hero"><div class="g1-container"><p class="g1-breadcrumb"><a href="/index.html">Ana Sayfa</a> / <a href="/siniflar/1-sinif/index.html">1. Sınıf</a> / <a href="'+base+'/'+p.subject+'.html">'+esc(sub.name)+'</a> / '+esc(title)+' Testi</p><div class="g1-hero-card"><span class="g1-kicker">10 Soruluk Test</span><h1>1. Sınıf '+esc(sub.name)+' - '+esc(title)+' Testi</h1><p class="g1-lead">Büyük seçeneklere dokun. Doğru cevap yeşil, yanlış cevap yumuşak kırmızı olur ve açıklama açılır.</p></div></div></section><section class="g1-section"><div class="g1-container" id="questionArea"></div></section></main>'+footer();var area=document.getElementById('questionArea');var correct=0,answered=0;area.innerHTML=q.map(function(item,i){return '<article class="g1-question" data-q="'+i+'"><h3>Soru '+(i+1)+': '+esc(item[0])+'</h3><div class="g1-options">'+item[1].map(function(opt,j){return '<button class="g1-option" type="button" data-answer="'+j+'">'+String.fromCharCode(65+j)+') '+esc(opt)+'</button>';}).join('')+'</div><div class="g1-explanation">'+esc(item[3])+'</div></article>';}).join('')+'<div id="testResult" class="g1-result"></div><div class="g1-actions"><button id="retryWrong" class="g1-btn yellow" type="button">Yanlışları Tekrar Çöz</button><a class="g1-btn white" href="'+base+'/'+p.subject+'/'+p.topic+'.html">Konuya Dön</a><a class="g1-btn soft" href="'+base+'/'+p.subject+'.html">Derse Dön</a></div>';area.addEventListener('click',function(e){var btn=e.target.closest('.g1-option');if(!btn||btn.disabled)return;var card=btn.closest('.g1-question');var index=parseInt(card.getAttribute('data-q'),10);var chosen=parseInt(btn.getAttribute('data-answer'),10);var ok=chosen===q[index][2];answered++;if(ok)correct++;card.querySelectorAll('.g1-option').forEach(function(b){b.disabled=true;});btn.classList.add(ok?'correct':'wrong');card.querySelectorAll('.g1-option')[q[index][2]].classList.add('correct');card.querySelector('.g1-explanation').classList.add('show');if(answered===q.length){var wrong=q.length-correct;var percent=Math.round(correct/q.length*100);var point=Math.max(0,Math.min(100,correct*10-wrong*4+(correct>=8?6:0)));document.getElementById('testResult').classList.add('show');document.getElementById('testResult').innerHTML='<h2>Test Sonucu</h2><p>Doğru: <strong>'+correct+'</strong> · Yanlış: <strong>'+wrong+'</strong> · Başarı: <strong>%'+percent+'</strong></p><p>Öğrenme Puanı: <strong>'+point+' / 100</strong></p>';}});document.getElementById('retryWrong').addEventListener('click',function(){location.href=base+'/'+p.subject+'/'+p.topic+'-test.html';});}
  function init(){var mode=document.body.dataset.mode;if(mode==='subject')renderSubject();if(mode==='topic')renderTopic();if(mode==='test')renderTest();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
