(function(){
var students=[
{name:'Ada K.',skill:'MAT.2.1.1 Onluk-birlik',q:8,status:'active',wrong:1,screen:18,work:16,score:86,accuracy:88,speed:'+12%',pattern:'Hızlı ve tutarlı'},
{name:'Efe D.',skill:'MAT.2.3.2 Onluk bozarak çıkarma',q:5,status:'help',wrong:3,screen:22,work:9,score:42,accuracy:44,speed:'-18%',pattern:'Onluk bozma adımında kavramsal eksik'},
{name:'Mira S.',skill:'MAT.2.2.1 Eldeli toplama',q:10,status:'active',wrong:0,screen:17,work:15,score:100,accuracy:96,speed:'+9%',pattern:'Mastery seviyesinde'},
{name:'Kerem A.',skill:'MAT.2.5.1 Nesne grafiği',q:3,status:'idle',wrong:0,screen:31,work:7,score:55,accuracy:62,speed:'-26%',pattern:'Ekranda bekleme süresi yüksek'},
{name:'Defne Y.',skill:'MAT.2.4.1 Geometrik şekiller',q:6,status:'active',wrong:1,screen:20,work:18,score:74,accuracy:78,speed:'+4%',pattern:'Kenar-köşe saymada küçük hata'},
{name:'Can B.',skill:'MAT.2.6.1 Yön-konum',q:4,status:'help',wrong:3,screen:19,work:11,score:39,accuracy:41,speed:'-11%',pattern:'Yön yönergelerini ters okuyor'},
{name:'Elif N.',skill:'MAT.2.2.2 Toplamı tahmin',q:7,status:'active',wrong:2,screen:16,work:14,score:68,accuracy:71,speed:'+3%',pattern:'Tahminde yuvarlama kararsız'},
{name:'Arda T.',skill:'MAT.2.3.1 Zihinden çıkarma',q:2,status:'idle',wrong:0,screen:25,work:6,score:51,accuracy:58,speed:'-20%',pattern:'Aktif çözüm oranı düşük'}
];
var trouble=[
['MAT.2.3.2','42 - 18 çıkarma problemi','58%','Akıllı tahtaya yansıt'],['MAT.2.6.1','2 kare sağ, 1 kare yukarı','37%','Yön oyunu ata'],['MAT.2.2.2','38 + 21 yaklaşık sonuç','29%','Yuvarlama tekrarı'],['MAT.2.5.1','Meyve grafiği fark bulma','24%','Grafik okuma mini seti']
];
var auditRows=[['09:12','Ada K.','MAT.2.1.1','18 sn','B','Doğru'],['09:13','Efe D.','MAT.2.3.2','46 sn','C','Yanlış'],['09:15','Mira S.','MAT.2.2.1','13 sn','A','Doğru'],['09:17','Kerem A.','MAT.2.5.1','184 sn','-','Boşta'],['09:18','Can B.','MAT.2.6.1','52 sn','D','Yanlış'],['09:19','Efe D.','MAT.2.3.2','61 sn','B','Yanlış'],['09:21','Can B.','MAT.2.6.1','48 sn','A','Yanlış'],['09:23','Defne Y.','MAT.2.4.1','21 sn','C','Doğru']];
var skills=[['MAT.2.1.1','Onluk ve birlikleri modeller',86,'İlerliyor'],['MAT.2.2.1','Eldeli toplama yapar',91,'Mastery yakını'],['MAT.2.3.2','Onluk bozarak çıkarma yapar',42,'Kırmızı bayrak'],['MAT.2.4.1','Şekil ve cisimleri ayırt eder',74,'Pekiştirme'],['MAT.2.5.1','Nesne grafiğini yorumlar',63,'İzlemeli'],['MAT.2.6.1','Yön ve konum yönergesi izler',39,'Kırmızı bayrak']];
function $(id){return document.getElementById(id)}
function qsa(sel,root){return Array.prototype.slice.call((root||document).querySelectorAll(sel))}
function statusText(s){return s==='help'?'Kırmızı bayrak':s==='idle'?'Boşta':'Aktif'}
function statusClass(s){return s==='help'?'bad':s==='idle'?'wait':'good'}
function scoreClass(score){return score<50?'red':score<75?'amber':'green'}
function initTabs(){qsa('[data-view]').forEach(function(btn){btn.addEventListener('click',function(){showView(btn.dataset.view);qsa('[data-view]').forEach(function(b){b.classList.toggle('active',b===btn)})})});qsa('[data-view-jump]').forEach(function(btn){btn.addEventListener('click',function(){showView(btn.dataset.viewJump);var menu=document.querySelector('[data-view="'+btn.dataset.viewJump+'"]');if(menu)menu.click()})})}
function showView(id){qsa('.oys-view').forEach(function(v){v.classList.toggle('active',v.id===id)})}
function updateMetrics(){var active=students.filter(function(s){return s.status==='active'}).length,flags=students.filter(function(s){return s.status==='help'}).length,avg=Math.round(students.reduce(function(t,s){return t+s.accuracy},0)/students.length);if($('metricActive'))$('metricActive').textContent=active;if($('metricFlags'))$('metricFlags').textContent=flags;if($('metricAccuracy'))$('metricAccuracy').textContent=avg+'%'}
function renderWall(){var el=$('wallDashboard');if(!el)return;var correct=Math.round(students.reduce(function(t,s){return t+s.accuracy},0)/students.length),wrong=100-correct,flags=students.filter(function(s){return s.status==='help'}).length;el.innerHTML='<div class="wall-card"><div class="donut" data-label="'+correct+'%"></div><span>Doğru oranı</span></div><div class="wall-card"><strong>'+wrong+'%</strong><span>Yanlış oranı</span></div><div class="wall-card"><strong>'+flags+'</strong><span>Kırmızı bayrak</span></div>'}
function renderLive(){var box=$('liveGrid');if(!box)return;box.innerHTML=students.map(function(s,i){var cls=scoreClass(s.score);return '<button class="student-tile '+s.status+'" data-student="'+i+'"><span class="name">'+s.name+'</span><span class="status-pill '+statusClass(s.status)+'">'+statusText(s.status)+'</span><span class="skill">'+s.skill+'</span><b>Soru '+s.q+'</b><span class="muted">Üst üste yanlış: '+s.wrong+'</span><div class="mini-score"><b>SmartScore '+s.score+'</b><span class="smart-track"><span class="'+cls+'" style="width:'+s.score+'%"></span></span></div></button>'}).join('');qsa('[data-student]',box).forEach(function(tile){tile.addEventListener('click',function(){var s=students[Number(tile.dataset.student)];$('selectedStudent').textContent=s.name+' seçildi. AI özeti: '+s.pattern;$('hintMessage').value=s.name+' için ipucu: '+(s.status==='help'?'Aynı kazanımda 3+ hata var; önce daha kolay örnekle başlayalım.':'Çözüm adımını sesli düşün ve cevabını kontrol et.')})})}
function renderRecommendations(){var el=$('recommendationList');if(!el)return;var recs=students.filter(function(s){return s.score<75||s.status==='help'||s.status==='idle'}).map(function(s){var flag=s.status==='help'?' flag':'';return '<article class="recommendation-card'+flag+'"><h3><span>'+s.name+'</span><span>SmartScore '+s.score+'</span></h3><p><b>AI özeti:</b> '+s.pattern+'.</p><p><b>Öneri:</b> '+(s.status==='help'?'Alt seviye 3 alıştırma ve öğretmen ipucu ata.':s.status==='idle'?'Aktif süre takibi ve kısa görev ata.':'Pekiştirme seti ata.')+'</p><div class="rec-actions"><button class="oys-btn primary">3 alıştırma ata</button><button class="oys-btn">Veli notu hazırla</button></div></article>'}).join('');el.innerHTML=recs}
function renderGroups(){var el=$('groupList');if(!el)return;el.innerHTML='<article class="group-card"><h3>Onluk bozma destek grubu <span>2 öğrenci</span></h3><p>Benzer hata: eksilenden onluk bozma adımını atlıyorlar.</p><div class="group-members"><span>Efe D.</span><span>Arda T.</span></div></article><article class="group-card"><h3>Yön-konum grubu <span>2 öğrenci</span></h3><p>Benzer hata: sağ-sol yönergesini ters uygulama.</p><div class="group-members"><span>Can B.</span><span>Kerem A.</span></div></article><article class="group-card"><h3>Mastery uzatma grubu <span>2 öğrenci</span></h3><p>SmartScore yüksek; zorlayıcı problem seti önerilir.</p><div class="group-members"><span>Mira S.</span><span>Ada K.</span></div></article>'}
function renderCurriculum(){var el=$('curriculumList');if(!el)return;el.innerHTML=skills.map(function(s){var cls=scoreClass(s[2]);return '<article class="curriculum-card"><div><b>'+s[0]+' - '+s[1]+'</b><small>'+s[3]+'</small><div class="smart-track" style="margin-top:8px"><span class="'+cls+'" style="width:'+s[2]+'%"></span></div></div><div class="mastery">'+s[2]+'/100</div></article>'}).join('')}
function renderAnalytics(){var tb=$('troubleTable');if(tb)tb.innerHTML=trouble.map(function(r){return '<tr class="'+(parseInt(r[2],10)>40?'risk-row':'')+'"><td data-label="Kazanım">'+r[0]+'</td><td data-label="Soru">'+r[1]+'</td><td data-label="Hata">'+r[2]+'</td><td data-label="Aksiyon"><button class="oys-btn" data-project="'+r[1]+'">'+r[3]+'</button></td></tr>'}).join('');var trends=$('trendList');if(trends)trends.innerHTML=students.slice(0,6).map(function(s){var cls=scoreClass(s.accuracy);return '<div class="chart-row"><b>'+s.name+' <small>'+s.speed+'</small></b><div class="bar"><span class="'+cls+'" style="width:'+s.accuracy+'%"></span></div><strong>'+s.accuracy+'%</strong></div>'}).join('');var align=$('alignmentList');if(align)align.innerHTML=skills.map(function(s){return '<article class="alignment-card '+(s[2]>=90?'mastered':s[2]<50?'risk':'')+'"><b>'+s[0]+'</b><p>'+s[1]+'</p><strong>'+s[2]+'</strong></article>'}).join('');qsa('[data-project]').forEach(function(b){b.addEventListener('click',function(){projectQuestion(b.dataset.project)})})}
function renderAudit(){var tbody=$('auditTableBody');if(tbody)tbody.innerHTML=auditRows.map(function(r){return '<tr class="'+(r[5]==='Yanlış'?'risk-row':'')+'"><td data-label="Saat">'+r[0]+'</td><td data-label="Öğrenci">'+r[1]+'</td><td data-label="Kazanım">'+r[2]+'</td><td data-label="Düşünme">'+r[3]+'</td><td data-label="Şık">'+r[4]+'</td><td data-label="Sonuç">'+r[5]+'</td></tr>'}).join('');var screen=$('screenWorkRows');if(screen)screen.innerHTML=students.map(function(s){var ratio=Math.round(s.work/s.screen*100);return '<div class="chart-row"><b>'+s.name+'</b><div class="bar"><span class="'+(ratio<45?'red':ratio<70?'amber':'green')+'" style="width:'+ratio+'%"></span></div><strong>'+ratio+'%</strong></div>'}).join('')}
function initAccordion(){qsa('.accordion-head').forEach(function(btn){btn.addEventListener('click',function(){btn.closest('.accordion-item').classList.toggle('open')})})}
function tickLive(){var i=Math.floor(Math.random()*students.length),s=students[i];if(s.status==='active')s.q=Math.min(10,s.q+1);if(Math.random()>.78)s.score=Math.max(25,Math.min(100,s.score+(Math.random()>.5?4:-5)));if(Math.random()>.86){s.status='help';s.wrong=3}renderLive();renderWall();updateMetrics();var log=$('wsLog');if(log){var li=document.createElement('li');li.textContent=new Date().toLocaleTimeString('tr-TR')+' Live Hub: '+s.name+' soru '+s.q+' / '+s.skill+' / SmartScore '+s.score;log.prepend(li);while(log.children.length>6)log.lastChild.remove()}}
function projectQuestion(text){var w=window.open('','_blank');if(!w)return;w.document.write('<title>Akıllı Tahta</title><style>body{font-family:Inter,Arial;margin:0;display:grid;place-items:center;min-height:100vh;background:#0f172a;color:white}main{max-width:900px;padding:48px}h1{font-size:48px}p{font-size:32px;line-height:1.4}.hint{color:#ffbf00}</style><main><h1>En Çok Yanlış Yapılan Soru</h1><p>'+text+'</p><p class="hint">Önce verilenleri işaretleyelim, sonra çözüm adımını birlikte kuralım.</p></main>');w.document.close()}
function printCertificate(){var top=students.filter(function(s){return s.score>=100})[0]||students[2];var w=window.open('','_blank');if(!w)return;w.document.write('<title>Başarı Sertifikası</title><style>@page{size:A4 landscape}body{font-family:Inter,Arial;display:grid;place-items:center;min-height:100vh;margin:0;background:#f6f8fb}.cert{width:900px;height:620px;border:12px solid #50c878;background:white;padding:54px;text-align:center}h1{font-size:46px}h2{font-size:34px;color:#2563eb}.seal{margin:24px auto;width:130px;height:130px;border-radius:50%;display:grid;place-items:center;background:#ffbf00;font-size:42px;font-weight:800}</style><section class="cert"><h1>e-kurs.com Başarı Sertifikası</h1><p>Bu belge</p><h2>'+top.name+'</h2><p>'+top.skill+' kazanımında 100 SmartScore ustalık hedefine ulaştığı için verilmiştir.</p><div class="seal">100</div><p>Öğretmen Onayı</p></section>');w.document.close();w.print()}
function downloadCsv(){var rows=[['Öğrenci','Kazanım','Soru','Durum','SmartScore','Doğruluk','AI Özeti']].concat(students.map(function(s){return [s.name,s.skill,s.q,statusText(s.status),s.score,s.accuracy+'%',s.pattern]}));var csv=rows.map(function(r){return r.map(function(c){return '"'+String(c).replace(/"/g,'""')+'"'}).join(',')}).join('\n');var blob=new Blob([csv],{type:'text/csv;charset=utf-8'});var url=URL.createObjectURL(blob);var a=document.createElement('a');a.href=url;a.download='e-kurs-live-hub-rapor.csv';a.click();URL.revokeObjectURL(url)}
function createParentPdf(){var w=window.open('','_blank');if(!w)return;w.document.write('<title>Veli PDF Raporu</title><style>body{font-family:Inter,Arial;padding:28px}h1{font-size:22px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px;text-align:left}</style><h1>e-kurs.com Veli Raporu</h1><p>SmartScore, trend ve AI öneri özeti.</p><table><tr><th>Öğrenci</th><th>SmartScore</th><th>AI Özeti</th></tr>'+students.map(function(s){return '<tr><td>'+s.name+'</td><td>'+s.score+'</td><td>'+s.pattern+'</td></tr>'}).join('')+'</table>');w.document.close();w.print()}
function initExports(){qsa('[data-export="csv"]').forEach(function(b){b.addEventListener('click',downloadCsv)});qsa('[data-export="pdf"]').forEach(function(b){b.addEventListener('click',createParentPdf)});qsa('[id^="printCertificate"]').forEach(function(b){b.addEventListener('click',printCertificate)});var pq=$('projectWorstQuestion');if(pq)pq.addEventListener('click',function(){projectQuestion(trouble[0][1])})}
function sendHint(){var msg=$('hintMessage'),target=$('selectedStudent'),log=$('wsLog');if(log&&msg&&target){var li=document.createElement('li');li.textContent='Öğretmen müdahalesi: '+target.textContent+' Mesaj: '+msg.value;log.prepend(li)}}
function init(){initTabs();initAccordion();renderLive();renderWall();renderRecommendations();renderGroups();renderCurriculum();renderAnalytics();renderAudit();updateMetrics();initExports();var send=$('sendHint');if(send)send.addEventListener('click',sendHint);var rescue=$('assignRescue');if(rescue)rescue.addEventListener('click',function(){showView('recommendations');var menu=document.querySelector('[data-view="recommendations"]');if(menu)menu.click()});if($('liveGrid'))setInterval(tickLive,4200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
