(function(){
var students=[
{name:'Ada K.',skill:'MAT.2.1.1 Onluk-birlik',q:8,status:'active',wrong:1,screen:18,work:16,score:86},
{name:'Efe D.',skill:'MAT.2.3.2 Onluk bozarak çıkarma',q:5,status:'help',wrong:3,screen:22,work:9,score:42},
{name:'Mira S.',skill:'MAT.2.2.1 Eldeli toplama',q:10,status:'active',wrong:0,screen:17,work:15,score:94},
{name:'Kerem A.',skill:'MAT.2.5.1 Nesne grafiği',q:3,status:'idle',wrong:0,screen:31,work:7,score:55},
{name:'Defne Y.',skill:'MAT.2.4.1 Geometrik şekiller',q:6,status:'active',wrong:1,screen:20,work:18,score:74},
{name:'Can B.',skill:'MAT.2.6.1 Yön-konum',q:4,status:'help',wrong:3,screen:19,work:11,score:39},
{name:'Elif N.',skill:'MAT.2.2.2 Toplamı tahmin',q:7,status:'active',wrong:2,screen:16,work:14,score:68},
{name:'Arda T.',skill:'MAT.2.3.1 Zihinden çıkarma',q:2,status:'idle',wrong:0,screen:25,work:6,score:51}
];
var auditRows=[
['09:12','Ada K.','MAT.2.1.1','18 sn','B','Doğru'],['09:13','Efe D.','MAT.2.3.2','46 sn','C','Yanlış'],['09:15','Mira S.','MAT.2.2.1','13 sn','A','Doğru'],['09:17','Kerem A.','MAT.2.5.1','184 sn','-','Boşta'],['09:18','Can B.','MAT.2.6.1','52 sn','D','Yanlış'],['09:19','Efe D.','MAT.2.3.2','61 sn','B','Yanlış'],['09:21','Can B.','MAT.2.6.1','48 sn','A','Yanlış'],['09:23','Defne Y.','MAT.2.4.1','21 sn','C','Doğru']
];
var skills=[
['MAT.2.1.1','Onluk ve birlikleri modeller','12 öğrenci hazır'],['MAT.2.2.1','Eldeli toplama yapar','8 öğrenci tekrar istiyor'],['MAT.2.3.2','Onluk bozarak çıkarma yapar','Kırmızı alarm'],['MAT.2.4.1','Şekil ve cisimleri ayırt eder','Sınıf ortalaması iyi'],['MAT.2.5.1','Nesne grafiğini yorumlar','6 öğrenci yavaş'],['MAT.2.6.1','Yön ve konum yönergesi izler','2 öğrenci yardım istiyor']
];
function $(id){return document.getElementById(id)}
function qsa(sel,root){return Array.prototype.slice.call((root||document).querySelectorAll(sel))}
function initTabs(){qsa('[data-view]').forEach(function(btn){btn.addEventListener('click',function(){qsa('[data-view]').forEach(function(b){b.classList.remove('active')});qsa('.oys-view').forEach(function(v){v.classList.remove('active')});btn.classList.add('active');$(btn.dataset.view).classList.add('active')})})}
function statusText(s){return s==='help'?'Yardım gerekiyor':s==='idle'?'Boşta':'Aktif'}
function statusClass(s){return s==='help'?'bad':s==='idle'?'wait':'good'}
function renderLive(){var box=$('liveGrid');if(!box)return;box.innerHTML=students.map(function(s,i){return '<button class="student-tile '+s.status+'" data-student="'+i+'"><span class="name">'+s.name+'</span><span class="status-pill '+statusClass(s.status)+'">'+statusText(s.status)+'</span><span class="skill">'+s.skill+'</span><b>Soru '+s.q+'</b><span class="muted">Üst üste yanlış: '+s.wrong+'</span></button>'}).join('');qsa('[data-student]',box).forEach(function(tile){tile.addEventListener('click',function(){var s=students[Number(tile.dataset.student)];$('selectedStudent').textContent=s.name+' için ipucu hazırlandı.';$('hintMessage').value='Bu soruda önce onlukları ayır, sonra birlikleri kontrol et. Sana küçük bir ipucu gönderiyorum.'})})}
function tickLive(){var i=Math.floor(Math.random()*students.length),s=students[i];if(s.status==='active')s.q=Math.min(10,s.q+1);if(Math.random()>.72)s.status=s.status==='idle'?'active':s.status;if(Math.random()>.84){s.status='help';s.wrong=3}renderLive();var log=$('wsLog');if(log){var li=document.createElement('li');li.textContent=new Date().toLocaleTimeString('tr-TR')+' WebSocket olayı: '+s.name+' soru '+s.q+' / '+s.skill;log.prepend(li);while(log.children.length>6)log.lastChild.remove()}}
function renderAudit(){var tbody=$('auditTableBody');if(!tbody)return;tbody.innerHTML=auditRows.map(function(r){return '<tr class="'+(r[5]==='Yanlış'?'risk-row':'')+'"><td data-label="Saat">'+r[0]+'</td><td data-label="Öğrenci">'+r[1]+'</td><td data-label="Kazanım">'+r[2]+'</td><td data-label="Düşünme">'+r[3]+'</td><td data-label="Şık">'+r[4]+'</td><td data-label="Sonuç">'+r[5]+'</td></tr>'}).join('');var screen=$('screenWorkRows');if(screen){screen.innerHTML=students.map(function(s){var ratio=Math.round(s.work/s.screen*100);return '<div class="chart-row"><b>'+s.name+'</b><div class="bar"><span class="'+(ratio<45?'red':ratio<70?'amber':'green')+'" style="width:'+ratio+'%"></span></div><strong>'+ratio+'%</strong></div>'}).join('')}}
function renderSkills(){var list=$('skillList');if(!list)return;list.innerHTML=skills.map(function(s,i){return '<div class="skill-row '+(i===2?'pin':'')+'"><div><b>'+s[0]+' - '+s[1]+'</b><small>'+s[2]+'</small></div><button class="oys-btn" data-pin="'+i+'">Yıldızla</button></div>'}).join('');qsa('[data-pin]',list).forEach(function(btn){btn.addEventListener('click',function(){btn.closest('.skill-row').classList.toggle('pin');btn.textContent=btn.closest('.skill-row').classList.contains('pin')?'Yıldızlandı':'Yıldızla'})})}
function initAccordion(){qsa('.accordion-head').forEach(function(btn){btn.addEventListener('click',function(){btn.closest('.accordion-item').classList.toggle('open')})})}
function downloadCsv(){var rows=[['Öğrenci','Kazanım','Soru','Durum','Ekran dk','Aktif dk','SmartScore']].concat(students.map(function(s){return [s.name,s.skill,s.q,statusText(s.status),s.screen,s.work,s.score]}));var csv=rows.map(function(r){return r.map(function(c){return '"'+String(c).replace(/"/g,'""')+'"'}).join(',')}).join('\n');var blob=new Blob([csv],{type:'text/csv;charset=utf-8'});var url=URL.createObjectURL(blob);var a=document.createElement('a');a.href=url;a.download='e-kurs-oys-rapor.csv';a.click();URL.revokeObjectURL(url)}
function createParentPdf(){var w=window.open('','_blank');if(!w)return;w.document.write('<title>Veli PDF Raporu</title><style>body{font-family:Inter,Arial;padding:28px}h1{font-size:22px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px;text-align:left}</style><h1>e-kurs.com Veli Raporu</h1><p>Demo rapor çıktısı. Canlı sistemde bu alan print-ready PDF servisine bağlanacaktır.</p><table><tr><th>Öğrenci</th><th>SmartScore</th><th>Durum</th></tr>'+students.map(function(s){return '<tr><td>'+s.name+'</td><td>'+s.score+'</td><td>'+statusText(s.status)+'</td></tr>'}).join('')+'</table>');w.document.close();w.print()}
function initExports(){qsa('[data-export="csv"]').forEach(function(b){b.addEventListener('click',downloadCsv)});qsa('[data-export="pdf"]').forEach(function(b){b.addEventListener('click',createParentPdf)});qsa('[data-export="whatsapp"]').forEach(function(a){a.addEventListener('click',function(){a.href='https://wa.me/?text='+encodeURIComponent('e-kurs.com veli raporu hazır. Öğrencinizin haftalık gelişim özetini panelden inceleyebilirsiniz.')})})}
function sendHint(){var msg=$('hintMessage'),target=$('selectedStudent');if(!msg||!target)return;var log=$('wsLog');if(log){var li=document.createElement('li');li.textContent='Öğretmen ipucu gönderdi: '+target.textContent+' Mesaj: '+msg.value;log.prepend(li)}}
function init(){initTabs();initAccordion();renderLive();renderAudit();renderSkills();initExports();var send=$('sendHint');if(send)send.addEventListener('click',sendHint);if($('liveGrid'))setInterval(tickLive,4200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
