(function(){
function $(id){return document.getElementById(id)}
function qsa(sel,root){return Array.prototype.slice.call((root||document).querySelectorAll(sel))}
function initNavStyle(){if(document.getElementById('studentNavRuntimeStyle'))return;var style=document.createElement('style');style.id='studentNavRuntimeStyle';style.textContent='.student-links{overflow-x:auto;scrollbar-width:thin}.student-links a{flex:0 0 auto}@media(min-width:1081px){.student-links{max-width:calc(100vw - 390px);padding-bottom:2px}}';document.head.appendChild(style)}
function initExpandedNav(){var nav=document.querySelector('.student-links');if(!nav)return;var links=[['Bugünkü Çalışmam','/ogrenci/bugunku-calismam.html'],['Testlerim','/ogrenci/testlerim.html'],['Mustafa Hoca’ya Sor','/ogrenci/mustafa-hocaya-sor.html'],['Veliye Göster','/ogrenci/veliye-goster.html'],['Ayarlar','/ogrenci/ayarlar.html']];var current=location.pathname.replace(/\/$/,'');links.forEach(function(item){if(nav.querySelector('a[href="'+item[1]+'"]'))return;var a=document.createElement('a');a.href=item[1];a.textContent=item[0];if(current===item[1].replace(/\.html$/,''))a.className='active';nav.appendChild(a)})}
function initMenu(){var nav=document.querySelector('.student-nav');var btn=document.querySelector('.student-menu');if(!nav||!btn)return;btn.addEventListener('click',function(){var open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',String(open))})}
function initScoreDemo(){qsa('[data-score-demo]').forEach(function(button){button.addEventListener('click',function(){var target=$(button.dataset.scoreDemo);if(!target)return;var current=Number(target.dataset.score||target.textContent.replace(/\D/g,''));var difficulty=Number(button.dataset.difficulty||1);var next=Math.min(100,current+Math.round(5*difficulty+2));target.dataset.score=String(next);target.textContent=next+' / 100';var bar=document.querySelector('[data-score-bar="'+target.id+'"]');if(bar)bar.style.setProperty('--value',next+'%')})})}
function initAnswers(){qsa('[data-answer]').forEach(function(button){button.addEventListener('click',function(){var group=button.closest('[data-question]');if(!group)return;qsa('[data-answer]',group).forEach(function(item){item.classList.remove('correct','wrong')});var correct=button.dataset.answer==='correct';button.classList.add(correct?'correct':'wrong');var explain=group.querySelector('.explain-box');if(explain){explain.classList.add('show');explain.textContent=correct?'Harika. 8’den sonra 9, 10, 11 diye üç adım saydın. Öğrenme puanın yükseldi.':'Yanlış ama çok yaklaştın. 8’den sonra 3 sayı ileri sayalım: 9, 10, 11. Doğru cevap 11. Şimdi benzer bir soru çözelim.'}var scoreTarget=$(group.dataset.scoreTarget||'');if(scoreTarget){var score=Number(scoreTarget.dataset.score||scoreTarget.textContent.replace(/\D/g,''));var next=correct?Math.min(100,score+6):Math.max(0,score-3);scoreTarget.dataset.score=String(next);scoreTarget.textContent=next+' / 100';var scoreBar=document.querySelector('[data-score-bar="'+scoreTarget.id+'"]');if(scoreBar)scoreBar.style.setProperty('--value',next+'%')}})})}
function initAssistant(){qsa('[data-tip]').forEach(function(button){button.addEventListener('click',function(){var box=$(button.dataset.tip);if(!box)return;box.textContent='Önce soruda ne istendiğini bulalım. Sonra küçük adımlarla ilerleyelim: birlikleri say, işlemi yaz, cevabı kontrol et.';box.classList.add('show')})})}
function initCopy(){qsa('[data-copy-summary]').forEach(function(button){button.addEventListener('click',function(){var target=$(button.dataset.copySummary);if(!target)return;var text=target.innerText.replace(/\n{2,}/g,'\n');if(navigator.clipboard)navigator.clipboard.writeText(text);button.textContent='Özet hazırlandı'})})}
function initReadAloud(){qsa('[data-read]').forEach(function(button){button.addEventListener('click',function(){var target=$(button.dataset.read);if(!target)return;var text=target.innerText||target.textContent;if(!('speechSynthesis' in window)){button.textContent='Ses desteği bu tarayıcıda yok';return}window.speechSynthesis.cancel();var utterance=new SpeechSynthesisUtterance(text);utterance.lang='tr-TR';utterance.rate=.88;window.speechSynthesis.speak(utterance)})})}
function initInterestRewrite(){qsa('[data-rewrite]').forEach(function(button){button.addEventListener('click',function(){var out=$(button.dataset.rewrite);var select=$(button.dataset.interest);if(!out||!select)return;var examples={Uzay:'Bir astronotun 28 yıldız rozeti vardı. Görevden sonra 15 rozet daha kazandı. Toplam kaç rozeti oldu?',Futbol:'Bir takımın 28 antrenman topu vardı. 15 top daha geldi. Toplam kaç top oldu?',Doğa:'Bahçede 28 fidan vardı. 15 fidan daha dikildi. Bahçede kaç fidan oldu?',Müzik:'Koroda 28 nota kartı vardı. Öğretmen 15 kart daha verdi. Toplam kaç kart oldu?'};out.textContent=examples[select.value]||examples.Uzay})})}
function init(){initNavStyle();initExpandedNav();initMenu();initScoreDemo();initAnswers();initAssistant();initCopy();initReadAloud();initInterestRewrite()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
