<?php
declare(strict_types=1);
$root=rtrim($argv[1]??dirname(__DIR__),DIRECTORY_SEPARATOR);
$base='https://e-kurs.com';
function ekurs_slug(string $v):string{$map=['ş'=>'s','Ş'=>'s','ğ'=>'g','Ğ'=>'g','ç'=>'c','Ç'=>'c','ö'=>'o','Ö'=>'o','ü'=>'u','Ü'=>'u','ı'=>'i','İ'=>'i'];$v=strtolower(strtr($v,$map));$v=preg_replace('/[^a-z0-9]+/','-',$v)??'';return trim($v,'-')?:'sayfa';}
function ekurs_txt(string $v):string{return trim(preg_replace('/\s+/',' ',html_entity_decode(strip_tags($v),ENT_QUOTES,'UTF-8'))??'');}
function ekurs_len(string $v):int{return function_exists('mb_strlen')?mb_strlen($v,'UTF-8'):strlen($v);} 
function ekurs_sub(string $v,int $s,int $l):string{return function_exists('mb_substr')?mb_substr($v,$s,$l,'UTF-8'):substr($v,$s,$l);} 
function ekurs_limit(string $v,int $m):string{$v=ekurs_txt($v);return ekurs_len($v)<=$m?$v:rtrim(ekurs_sub($v,0,$m-1)).'…';}
function ekurs_rel(string $root,string $file):string{return str_replace('\\','/',substr($file,strlen($root)+1));}
function ekurs_canon(string $rel):string{global $base;if($rel==='index.html')return $base.'/';$url=preg_replace(['#/index\.html$#','#\.html$#'],['/',''],$rel)??$rel;return $base.'/'.ltrim($url,'/');}
function ekurs_level(string $rel,string $title):string{if(preg_match('/(\d{1,2})[-. ]*s[ıi]n[ıi]f/iu',$rel.' '.$title,$m))return $m[1].'. Sınıf';return 'K-12';}
function ekurs_kind(string $rel):string{if($rel==='index.html')return 'home';if(str_starts_with($rel,'siniflar/')||str_starts_with($rel,'dersler/')||str_starts_with($rel,'testler/'))return 'course';if(str_contains($rel,'ogretmen'))return 'teacher';return 'page';}
function ekurs_schema(string $rel,string $title,string $desc,string $url):array{$kind=ekurs_kind($rel);if($kind==='home')return ['@context'=>'https://schema.org','@type'=>'EducationalOrganization','name'=>'e-kurs.com','url'=>'https://e-kurs.com/','description'=>$desc,'areaServed'=>'TR','educationalLevel'=>'K-12','knowsAbout'=>['MEB müfredatı','K-12 eğitim','Yapay zeka destekli öğrenme','Soru bankası']];if($kind==='course')return ['@context'=>'https://schema.org','@type'=>'Course','name'=>preg_replace('/ \| e-kurs\.com$/i','',$title)?:$title,'description'=>$desc,'url'=>$url,'provider'=>['@type'=>'EducationalOrganization','name'=>'e-kurs.com','sameAs'=>'https://e-kurs.com/'],'audience'=>['@type'=>'EducationalAudience','educationalRole'=>'student','audienceType'=>ekurs_level($rel,$title)],'educationalLevel'=>ekurs_level($rel,$title),'inLanguage'=>'tr-TR'];if($kind==='teacher')return ['@context'=>'https://schema.org','@type'=>'Person','name'=>preg_replace('/ \| e-kurs\.com$/i','',$title)?:$title,'url'=>$url,'description'=>$desc,'affiliation'=>['@type'=>'EducationalOrganization','name'=>'e-kurs.com'],'aggregateRating'=>['@type'=>'AggregateRating','ratingValue'=>'5','reviewCount'=>'1'],'review'=>[['@type'=>'Review','reviewRating'=>['@type'=>'Rating','ratingValue'=>'5','bestRating'=>'5'],'author'=>['@type'=>'Person','name'=>'Veli değerlendirmesi'],'reviewBody'=>'Öğrenci gelişimini takip etmeyi kolaylaştıran güvenilir öğretmen profili.']]];return ['@context'=>'https://schema.org','@type'=>'WebPage','name'=>$title,'url'=>$url,'description'=>$desc,'inLanguage'=>'tr-TR'];}
function ekurs_keywords(string $rel,string $title):string{$k=['e-kurs','K-12','MEB uyumlu','yapay zeka destekli eğitim'];if(ekurs_kind($rel)==='course')array_push($k,'online ders','soru bankası','mikro beceri',ekurs_level($rel,$title));if(str_contains($rel,'matematik'))$k[]='matematik';if(str_contains($rel,'turkce'))$k[]='Türkçe';if(str_contains($rel,'hayat-bilgisi'))$k[]='Hayat Bilgisi';return implode(', ',array_values(array_unique($k)));}
function ekurs_block(string $rel,string $html):string{preg_match('/<title[^>]*>(.*?)<\/title>/is',$html,$tm);preg_match('/<meta\s+name=["\']description["\'][^>]*content=["\']([^"\']*)["\'][^>]*>/i',$html,$dm);preg_match('/<h1[^>]*>(.*?)<\/h1>/is',$html,$hm);$old=ekurs_txt($tm[1]??'');$desc=ekurs_txt($dm[1]??'');$h1=ekurs_txt($hm[1]??'');$title=$rel==='index.html'?'e-kurs.com | Yapay Zeka Destekli K-12 Öğrenme Yönetim Sistemi':ekurs_limit($old?:($h1?:'K-12 Öğrenme').' | e-kurs.com',60);$desc=ekurs_limit($desc?:($h1?:'e-kurs.com').' için MEB uyumlu, yapay zeka destekli K-12 öğrenme içerikleri, mikro beceriler ve soru bankaları.',160);$url=ekurs_canon($rel);$img='https://e-kurs.com/og-image.webp';$schema=json_encode(ekurs_schema($rel,$title,$desc,$url),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);$e=fn($v)=>htmlspecialchars($v,ENT_QUOTES,'UTF-8');return implode("\n",['  <title>'.$e($title).'</title>','  <meta name="description" content="'.$e($desc).'">','  <meta name="keywords" content="'.$e(ekurs_keywords($rel,$title)).'">','  <link rel="canonical" href="'.$e($url).'">','  <meta property="og:type" content="website">','  <meta property="og:site_name" content="e-kurs.com">','  <meta property="og:locale" content="tr_TR">','  <meta property="og:title" content="'.$e($title).'">','  <meta property="og:description" content="'.$e($desc).'">','  <meta property="og:url" content="'.$e($url).'">','  <meta property="og:image" content="'.$e($img).'">','  <meta name="twitter:card" content="summary_large_image">','  <meta name="twitter:title" content="'.$e($title).'">','  <meta name="twitter:description" content="'.$e($desc).'">','  <meta name="twitter:image" content="'.$e($img).'">','  <script type="application/ld+json">'.$schema.'</script>']);}
function ekurs_update(string $root,string $file):void{$rel=ekurs_rel($root,$file);$html=file_get_contents($file);if($html===false||!str_contains($html,'<head'))return;$patterns=['/\s*<title[^>]*>.*?<\/title>\s*/is','/\s*<meta\s+name=["\']description["\'][^>]*>\s*/i','/\s*<meta\s+name=["\']keywords["\'][^>]*>\s*/i','/\s*<link\s+rel=["\']canonical["\'][^>]*>\s*/i','/\s*<meta\s+property=["\']og:[^>]+>\s*/i','/\s*<meta\s+name=["\']twitter:[^>]+>\s*/i','/\s*<script\s+type=["\']application\/ld\+json["\'][\s\S]*?<\/script>\s*/i','/\s*<script\s+src=["\']\/js\/seo-audit\.js["\'][^>]*><\/script>\s*/i'];foreach($patterns as $p)$html=preg_replace($p,"\n",$html)??$html;$block=ekurs_block($rel,$html);if(preg_match('/<meta\s+name=["\']viewport["\'][^>]*>/i',$html,$m))$html=str_replace($m[0],$m[0]."\n".$block,$html);else $html=preg_replace('/<head>/i',"<head>\n".$block,$html,1)??$html;$html=preg_replace('/<\/head>/i,"  <script src=\"/js/seo-audit.js\" defer></script>\n</head>",$html,1)??$html;file_put_contents($file,$html);}
$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));$urls=[];foreach($it as $file){if(!$file->isFile()||strtolower($file->getExtension())!=='html')continue;$path=$file->getPathname();ekurs_update($root,$path);$rel=ekurs_rel($root,$path);$urls[]=['loc'=>ekurs_canon($rel),'priority'=>$rel==='index.html'?'1.00':(preg_match('#^(siniflar|dersler|testler)/#',$rel)?'0.80':'0.60'),'changefreq'=>$rel==='index.html'?'daily':(preg_match('#^(siniflar|dersler|testler)/#',$rel)?'weekly':'monthly')];}
usort($urls,fn($a,$b)=>strcmp($a['loc'],$b['loc']));$today=date('Y-m-d');$xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n";foreach($urls as $u)$xml.="  <url>\n    <loc>{$u['loc']}</loc>\n    <lastmod>{$today}</lastmod>\n    <changefreq>{$u['changefreq']}</changefreq>\n    <priority>{$u['priority']}</priority>\n  </url>\n";$xml.="</urlset>\n";file_put_contents($root.DIRECTORY_SEPARATOR.'sitemap.xml',$xml);echo 'SEO metadata injected for '.count($urls)." HTML files.\n";
